#ifndef C0P_PARAM_OBJECTS_SURFER__US_20O0__SURFTIMECONST_5O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_20O0__SURFTIMECONST_5O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/surfer__us_20o0__surftimeconst_5o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/choice.h"
namespace c0p {
    template<typename SurferUs20O0Surftimeconst5O0GroupHomogeneousMemberAgentActiveStep>
    using SurferUs20O0Surftimeconst5O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity = SurferUs20O0Surftimeconst5O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst<SurferUs20O0Surftimeconst5O0GroupHomogeneousMemberAgentActiveStep>;
}

#endif
