#ifndef C0P_PARAM_OBJECTS_SURFER__US_0O2__SURFTIMEPREFACTOR_2O25_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_0O2__SURFTIMEPREFACTOR_2O25_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/static/surfer__us_0o2__surftimeprefactor_2o25/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/choice.h"
namespace c0p {
    template<typename SurferUs0O2Surftimeprefactor2O25GroupHomogeneousMemberAgentActiveStep>
    using SurferUs0O2Surftimeprefactor2O25GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity = SurferUs0O2Surftimeprefactor2O25GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst<SurferUs0O2Surftimeprefactor2O25GroupHomogeneousMemberAgentActiveStep>;
}

#endif
