#ifndef C0P_PARAM_OBJECTS_SURFER__US_8O0__SURFTIMEPREFACTOR_3O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_8O0__SURFTIMEPREFACTOR_3O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/surfer__us_8o0__surftimeprefactor_3o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/choice.h"
namespace c0p {
    template<typename SurferUs8O0Surftimeprefactor3O0GroupHomogeneousMemberAgentActiveStep>
    using SurferUs8O0Surftimeprefactor3O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity = SurferUs8O0Surftimeprefactor3O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst<SurferUs8O0Surftimeprefactor3O0GroupHomogeneousMemberAgentActiveStep>;
}

#endif
