#ifndef C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_1O0__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_SENSOR_VELOCITY_GRADIENTS_ACCURATE_PARAMETERS_H
#define C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_1O0__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_SENSOR_VELOCITY_GRADIENTS_ACCURATE_PARAMETERS_H
#pragma once

// app includes
#include "core/env/objects/object/agent/behaviour/sensor/velocity_gradients/accurate/prop.h"
#include "param/parameters.h"

namespace c0p {

// Accurate flow velocity gradients sensor parameters
struct SurferUs1O0Surftimeconst1O0Reorientationtime0O5GroupHomogeneousMemberAgentBehaviourSensorVelocityGradientsAccurateParameters {
};

}

#endif
