#ifndef C0P_PARAM_OBJECTS_SURFER__US_2O0__SURFTIMECONST_0O025_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_2O0__SURFTIMECONST_0O025_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/surfer__us_2o0__surftimeconst_0o025/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_direction/surf/choice.h"
namespace c0p {
    template<typename SurferUs2O0Surftimeconst0O025GroupHomogeneousMemberAgentActiveStep>
    using SurferUs2O0Surftimeconst0O025GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirection = SurferUs2O0Surftimeconst0O025GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirectionSurf<SurferUs2O0Surftimeconst0O025GroupHomogeneousMemberAgentActiveStep>;
}

#endif
