#ifndef C0P_PARAM_OBJECTS_SURFER__US_15O58__SURFTIMECONST_0O0__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_SURF_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_15O58__SURFTIMECONST_0O0__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_SURF_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// behaviour time horizon choice
#include "param/env/objects/surfer__us_15o58__surftimeconst_0o0__reorientationtime_0o5/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_direction/surf/_behaviour_time_horizon/choice.h"
// choose your behaviour
#include "core/env/objects/object/agent/behaviour/navigator/behaviour_direction/surf/exp/core.h"
#include "param/env/objects/surfer__us_15o58__surftimeconst_0o0__reorientationtime_0o5/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_direction/surf/exp/parameters.h"
namespace c0p {
    template<typename SurferUs15O58Surftimeconst0O0Reorientationtime0O5GroupHomogeneousMemberAgentActiveStep>
    using SurferUs15O58Surftimeconst0O0Reorientationtime0O5GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirectionSurf = AgentBehaviourNavigatorBehaviourDirectionSurfExp<SurferUs15O58Surftimeconst0O0Reorientationtime0O5GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirectionSurfExpParameters, SurferUs15O58Surftimeconst0O0Reorientationtime0O5GroupHomogeneousMemberAgentActiveStep, SurferUs15O58Surftimeconst0O0Reorientationtime0O5GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirectionSurfBehaviourTimeHorizon<SurferUs15O58Surftimeconst0O0Reorientationtime0O5GroupHomogeneousMemberAgentActiveStep>>;
}

#endif
