#ifndef C0P_PARAM_OBJECTS_SURFER__US_0O8__SURFTIMECONST_2O75_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_0O8__SURFTIMECONST_2O75_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/static/surfer__us_0o8__surftimeconst_2o75/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_direction/surf/choice.h"
namespace c0p {
    template<typename SurferUs0O8Surftimeconst2O75GroupHomogeneousMemberAgentActiveStep>
    using SurferUs0O8Surftimeconst2O75GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirection = SurferUs0O8Surftimeconst2O75GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirectionSurf<SurferUs0O8Surftimeconst2O75GroupHomogeneousMemberAgentActiveStep>;
}

#endif
