#ifndef C0P_PARAM_POST_OBJECTS_SURFER__US_1O0__SURFTIMECONST_9O0__REORIENTATIONTIME_2O0_PZ_GROUP_MEMBER_CHOICE_H
#define C0P_PARAM_POST_OBJECTS_SURFER__US_1O0__SURFTIMECONST_9O0__REORIENTATIONTIME_2O0_PZ_GROUP_MEMBER_CHOICE_H
#pragma once

// choose your post
#include "param/post/objects/surfer__us_1o0__surftimeconst_9o0__reorientationtime_2o0/pz/group/_member/passive/choice.h"

namespace c0p {
    template<typename TypeMemberStep>
    using PostSurferUs1O0Surftimeconst9O0Reorientationtime2O0PzGroupMember = PostSurferUs1O0Surftimeconst9O0Reorientationtime2O0PzGroupMemberPassive<TypeMemberStep>;
}

#endif
