#ifndef C0P_PARAM_OBJECTS_SURFER__US_2O0__SURFTIMEPREFACTOR_1O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_2O0__SURFTIMEPREFACTOR_1O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/surfer__us_2o0__surftimeprefactor_1o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/choice.h"
namespace c0p {
    template<typename SurferUs2O0Surftimeprefactor1O0GroupHomogeneousMemberAgentActiveStep>
    using SurferUs2O0Surftimeprefactor1O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity = SurferUs2O0Surftimeprefactor1O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst<SurferUs2O0Surftimeprefactor1O0GroupHomogeneousMemberAgentActiveStep>;
}

#endif
