#ifndef C0P_PARAM_OBJECTS_SURFER__US_7O0__SURFTIMECONST_10O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_7O0__SURFTIMECONST_10O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/surfer__us_7o0__surftimeconst_10o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_direction/surf/choice.h"
namespace c0p {
    template<typename SurferUs7O0Surftimeconst10O0GroupHomogeneousMemberAgentActiveStep>
    using SurferUs7O0Surftimeconst10O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirection = SurferUs7O0Surftimeconst10O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirectionSurf<SurferUs7O0Surftimeconst10O0GroupHomogeneousMemberAgentActiveStep>;
}

#endif
