#ifndef C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_2O0__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_2O0__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/surfer__us_1o0__surftimeconst_2o0__reorientationtime_0o5/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/choice.h"
namespace c0p {
    template<typename SurferUs1O0Surftimeconst2O0Reorientationtime0O5GroupHomogeneousMemberAgentActiveStep>
    using SurferUs1O0Surftimeconst2O0Reorientationtime0O5GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity = SurferUs1O0Surftimeconst2O0Reorientationtime0O5GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst<SurferUs1O0Surftimeconst2O0Reorientationtime0O5GroupHomogeneousMemberAgentActiveStep>;
}

#endif
