#ifndef C0P_PARAM_OBJECTS_SURFER__US_8O0__SURFTIMEPREFACTOR_0O75_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_SENSOR_VELOCITY_GRADIENTS_ACCURATE_PARAMETERS_H
#define C0P_PARAM_OBJECTS_SURFER__US_8O0__SURFTIMEPREFACTOR_0O75_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_SENSOR_VELOCITY_GRADIENTS_ACCURATE_PARAMETERS_H
#pragma once

// app includes
#include "core/env/objects/object/agent/behaviour/sensor/velocity_gradients/accurate/prop.h"
#include "param/parameters.h"

namespace c0p {

// Accurate flow velocity gradients sensor parameters
struct SurferUs8O0Surftimeprefactor0O75GroupHomogeneousMemberAgentBehaviourSensorVelocityGradientsAccurateParameters {
};

}

#endif
