#ifndef C0P_PARAM_OBJECTS_SURFER__US_9O0__SURFTIMECONST_6O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_9O0__SURFTIMECONST_6O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/surfer__us_9o0__surftimeconst_6o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/choice.h"
namespace c0p {
    template<typename SurferUs9O0Surftimeconst6O0GroupHomogeneousMemberAgentActiveStep>
    using SurferUs9O0Surftimeconst6O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity = SurferUs9O0Surftimeconst6O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst<SurferUs9O0Surftimeconst6O0GroupHomogeneousMemberAgentActiveStep>;
}

#endif
