#ifndef C0P_PARAM_OBJECTS_SURFER__US_0O5__SURFTIMECONST_8O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_0O5__SURFTIMECONST_8O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/surfer__us_0o5__surftimeconst_8o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_direction/surf/choice.h"
namespace c0p {
    template<typename SurferUs0O5Surftimeconst8O0GroupHomogeneousMemberAgentActiveStep>
    using SurferUs0O5Surftimeconst8O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirection = SurferUs0O5Surftimeconst8O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirectionSurf<SurferUs0O5Surftimeconst8O0GroupHomogeneousMemberAgentActiveStep>;
}

#endif
