#ifndef C0P_PARAM_INIT_OBJECTS_SURFER__US_1O0__SURFTIMECONST_3O0__REORIENTATIONTIME_0O5_ORIENT_GROUP_MEMBER_PASSIVE_POS_RANDOM_PARAMETERS_H
#define C0P_PARAM_INIT_OBJECTS_SURFER__US_1O0__SURFTIMECONST_3O0__REORIENTATIONTIME_0O5_ORIENT_GROUP_MEMBER_PASSIVE_POS_RANDOM_PARAMETERS_H
#pragma once

// app include
#include "core/init/objects/object/init/passive/axis/random/prop.h"

namespace c0p {

// Random object orientation initialisation parameters
struct InitSurferUs1O0Surftimeconst3O0Reorientationtime0O5OrientGroupMemberPassiveAxisRandomParameters {
};

}

#endif
