#ifndef C0P_PARAM_OBJECTS_SURFER__US_4O0__SURFTIMEPREFACTOR_3O75_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_4O0__SURFTIMEPREFACTOR_3O75_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/surfer__us_4o0__surftimeprefactor_3o75/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_direction/surf/choice.h"
namespace c0p {
    template<typename SurferUs4O0Surftimeprefactor3O75GroupHomogeneousMemberAgentActiveStep>
    using SurferUs4O0Surftimeprefactor3O75GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirection = SurferUs4O0Surftimeprefactor3O75GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirectionSurf<SurferUs4O0Surftimeprefactor3O75GroupHomogeneousMemberAgentActiveStep>;
}

#endif
