#ifndef C0P_PARAM_OBJECTS_SURFER__US_4O0__SURFTIMECONST_0O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_4O0__SURFTIMECONST_0O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// behaviour direction choice
#include "param/env/objects/surfer__us_4o0__surftimeconst_0o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_direction/choice.h"
#include "param/env/objects/surfer__us_4o0__surftimeconst_0o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/choice.h"
// choose your behaviour
#include "core/env/objects/object/agent/behaviour/navigator/swimmer/core.h"
#include "param/env/objects/surfer__us_4o0__surftimeconst_0o0/group/homogeneous/_member/agent/_behaviour/navigator/swimmer/parameters.h"
namespace c0p {
    template<typename SurferUs4O0Surftimeconst0O0GroupHomogeneousMemberAgentActiveStep>
    using SurferUs4O0Surftimeconst0O0GroupHomogeneousMemberAgentBehaviourNavigator = AgentBehaviourNavigatorSwimmer<SurferUs4O0Surftimeconst0O0GroupHomogeneousMemberAgentBehaviourNavigatorSwimmerParameters, SurferUs4O0Surftimeconst0O0GroupHomogeneousMemberAgentActiveStep, SurferUs4O0Surftimeconst0O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirection<SurferUs4O0Surftimeconst0O0GroupHomogeneousMemberAgentActiveStep>, SurferUs4O0Surftimeconst0O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity<SurferUs4O0Surftimeconst0O0GroupHomogeneousMemberAgentActiveStep>>;
}

#endif
