#ifndef C0P_PARAM_OBJECTS_SURFER__US_0O4__SURFTIMEPREFACTOR_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_0O4__SURFTIMEPREFACTOR_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/static/surfer__us_0o4__surftimeprefactor_0o5/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/choice.h"
namespace c0p {
    template<typename SurferUs0O4Surftimeprefactor0O5GroupHomogeneousMemberAgentActiveStep>
    using SurferUs0O4Surftimeprefactor0O5GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity = SurferUs0O4Surftimeprefactor0O5GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst<SurferUs0O4Surftimeprefactor0O5GroupHomogeneousMemberAgentActiveStep>;
}

#endif
