#ifndef C0P_PARAM_OBJECTS_SURFER__US_4O5__SURFTIMECONST_9O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_SENSOR_VELOCITY_GRADIENTS_ACCURATE_PARAMETERS_H
#define C0P_PARAM_OBJECTS_SURFER__US_4O5__SURFTIMECONST_9O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_SENSOR_VELOCITY_GRADIENTS_ACCURATE_PARAMETERS_H
#pragma once

// app includes
#include "core/env/objects/object/agent/behaviour/sensor/velocity_gradients/accurate/prop.h"
#include "param/parameters.h"

namespace c0p {

// Accurate flow velocity gradients sensor parameters
struct SurferUs4O5Surftimeconst9O0GroupHomogeneousMemberAgentBehaviourSensorVelocityGradientsAccurateParameters {
};

}

#endif
