#ifndef C0P_PARAM_OBJECTS_SURFER__US_15O58__SURFTIMECONST_3O0__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_SENSOR_DIRECTION_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_15O58__SURFTIMECONST_3O0__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_SENSOR_DIRECTION_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "core/env/objects/object/agent/behaviour/sensor/direction/accurate/core.h"
#include "param/env/objects/static/surfer__us_15o58__surftimeconst_3o0__reorientationtime_0o5/group/homogeneous/_member/agent/_behaviour/_sensor/direction/accurate/parameters.h"
namespace c0p {
    template<typename SurferUs15O58Surftimeconst3O0Reorientationtime0O5GroupHomogeneousMemberAgentActiveStep>
    using SurferUs15O58Surftimeconst3O0Reorientationtime0O5GroupHomogeneousMemberAgentBehaviourSensorDirection = AgentBehaviourSensorDirectionAccurate<SurferUs15O58Surftimeconst3O0Reorientationtime0O5GroupHomogeneousMemberAgentBehaviourSensorDirectionAccurateParameters, SurferUs15O58Surftimeconst3O0Reorientationtime0O5GroupHomogeneousMemberAgentActiveStep>;
}

#endif
