#ifndef C0P_PARAM_OBJECTS_SURFER__US_6O0__SURFTIMECONST_7O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_6O0__SURFTIMECONST_7O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/surfer__us_6o0__surftimeconst_7o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_direction/surf/choice.h"
namespace c0p {
    template<typename SurferUs6O0Surftimeconst7O0GroupHomogeneousMemberAgentActiveStep>
    using SurferUs6O0Surftimeconst7O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirection = SurferUs6O0Surftimeconst7O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirectionSurf<SurferUs6O0Surftimeconst7O0GroupHomogeneousMemberAgentActiveStep>;
}

#endif
