#ifndef C0P_PARAM_INIT_OBJECTS_PARAPETERS_H
#define C0P_PARAM_INIT_OBJECTS_PARAMETERS_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// COPY/REMOVE COMMAND ARE USED

// std include
#include <vector>
// app include
#include "core/init/objects/object/core.h"
#include "core/init/objects/prop.h"
// FLAG: INCLUDE OBJECT BEGIN
#include "param/init/objects/surfer__us_1o0__surftimeconst_1o0/parameters.h"
#include "param/init/objects/riser__us_1o0/parameters.h"
#include "param/init/objects/riser__us_0o5/parameters.h"
#include "param/init/objects/riser__us_1o5/parameters.h"
#include "param/init/objects/riser__us_2o0/parameters.h"
#include "param/init/objects/riser__us_2o5/parameters.h"
#include "param/init/objects/riser__us_3o0/parameters.h"
#include "param/init/objects/riser__us_3o5/parameters.h"
#include "param/init/objects/riser__us_4o0/parameters.h"
#include "param/init/objects/riser__us_4o5/parameters.h"
#include "param/init/objects/riser__us_5o0/parameters.h"
#include "param/init/objects/riser__us_6o0/parameters.h"
#include "param/init/objects/riser__us_7o0/parameters.h"
#include "param/init/objects/riser__us_8o0/parameters.h"
#include "param/init/objects/riser__us_9o0/parameters.h"
#include "param/init/objects/riser__us_10o0/parameters.h"
#include "param/init/objects/riser__us_15o0/parameters.h"
#include "param/init/objects/riser__us_20o0/parameters.h"
#include "param/init/objects/surfer__us_0o5__surftimeconst_1o0/parameters.h"
#include "param/init/objects/surfer__us_1o5__surftimeconst_1o0/parameters.h"
#include "param/init/objects/surfer__us_2o0__surftimeconst_1o0/parameters.h"
#include "param/init/objects/surfer__us_2o5__surftimeconst_1o0/parameters.h"
#include "param/init/objects/surfer__us_3o0__surftimeconst_1o0/parameters.h"
#include "param/init/objects/surfer__us_3o5__surftimeconst_1o0/parameters.h"
#include "param/init/objects/surfer__us_4o0__surftimeconst_1o0/parameters.h"
#include "param/init/objects/surfer__us_4o5__surftimeconst_1o0/parameters.h"
#include "param/init/objects/surfer__us_5o0__surftimeconst_1o0/parameters.h"
#include "param/init/objects/surfer__us_6o0__surftimeconst_1o0/parameters.h"
#include "param/init/objects/surfer__us_7o0__surftimeconst_1o0/parameters.h"
#include "param/init/objects/surfer__us_8o0__surftimeconst_1o0/parameters.h"
#include "param/init/objects/surfer__us_9o0__surftimeconst_1o0/parameters.h"
#include "param/init/objects/surfer__us_10o0__surftimeconst_1o0/parameters.h"
#include "param/init/objects/surfer__us_15o0__surftimeconst_1o0/parameters.h"
#include "param/init/objects/surfer__us_20o0__surftimeconst_1o0/parameters.h"
#include "param/init/objects/surfer__us_0o5__surftimeconst_0o0/parameters.h"
#include "param/init/objects/surfer__us_0o5__surftimeconst_2o0/parameters.h"
#include "param/init/objects/surfer__us_0o5__surftimeconst_3o0/parameters.h"
#include "param/init/objects/surfer__us_0o5__surftimeconst_4o0/parameters.h"
#include "param/init/objects/surfer__us_0o5__surftimeconst_5o0/parameters.h"
#include "param/init/objects/surfer__us_0o5__surftimeconst_6o0/parameters.h"
#include "param/init/objects/surfer__us_0o5__surftimeconst_7o0/parameters.h"
#include "param/init/objects/surfer__us_0o5__surftimeconst_8o0/parameters.h"
#include "param/init/objects/surfer__us_0o5__surftimeconst_9o0/parameters.h"
#include "param/init/objects/surfer__us_0o5__surftimeconst_10o0/parameters.h"
#include "param/init/objects/surfer__us_10o0__surftimeconst_0o0/parameters.h"
#include "param/init/objects/surfer__us_10o0__surftimeconst_2o0/parameters.h"
#include "param/init/objects/surfer__us_10o0__surftimeconst_3o0/parameters.h"
#include "param/init/objects/surfer__us_10o0__surftimeconst_4o0/parameters.h"
#include "param/init/objects/surfer__us_10o0__surftimeconst_5o0/parameters.h"
#include "param/init/objects/surfer__us_10o0__surftimeconst_6o0/parameters.h"
#include "param/init/objects/surfer__us_10o0__surftimeconst_7o0/parameters.h"
#include "param/init/objects/surfer__us_10o0__surftimeconst_8o0/parameters.h"
#include "param/init/objects/surfer__us_10o0__surftimeconst_9o0/parameters.h"
#include "param/init/objects/surfer__us_10o0__surftimeconst_10o0/parameters.h"
#include "param/init/objects/surfer__us_15o0__surftimeconst_0o0/parameters.h"
#include "param/init/objects/surfer__us_15o0__surftimeconst_2o0/parameters.h"
#include "param/init/objects/surfer__us_15o0__surftimeconst_3o0/parameters.h"
#include "param/init/objects/surfer__us_15o0__surftimeconst_4o0/parameters.h"
#include "param/init/objects/surfer__us_15o0__surftimeconst_5o0/parameters.h"
#include "param/init/objects/surfer__us_15o0__surftimeconst_6o0/parameters.h"
#include "param/init/objects/surfer__us_15o0__surftimeconst_7o0/parameters.h"
#include "param/init/objects/surfer__us_15o0__surftimeconst_8o0/parameters.h"
#include "param/init/objects/surfer__us_15o0__surftimeconst_9o0/parameters.h"
#include "param/init/objects/surfer__us_15o0__surftimeconst_10o0/parameters.h"
#include "param/init/objects/surfer__us_1o0__surftimeconst_0o0/parameters.h"
#include "param/init/objects/surfer__us_1o0__surftimeconst_2o0/parameters.h"
#include "param/init/objects/surfer__us_1o0__surftimeconst_3o0/parameters.h"
#include "param/init/objects/surfer__us_1o0__surftimeconst_4o0/parameters.h"
#include "param/init/objects/surfer__us_1o0__surftimeconst_5o0/parameters.h"
#include "param/init/objects/surfer__us_1o0__surftimeconst_6o0/parameters.h"
#include "param/init/objects/surfer__us_1o0__surftimeconst_7o0/parameters.h"
#include "param/init/objects/surfer__us_1o0__surftimeconst_8o0/parameters.h"
#include "param/init/objects/surfer__us_1o0__surftimeconst_9o0/parameters.h"
#include "param/init/objects/surfer__us_1o0__surftimeconst_10o0/parameters.h"
#include "param/init/objects/surfer__us_1o5__surftimeconst_0o0/parameters.h"
#include "param/init/objects/surfer__us_1o5__surftimeconst_2o0/parameters.h"
#include "param/init/objects/surfer__us_1o5__surftimeconst_3o0/parameters.h"
#include "param/init/objects/surfer__us_1o5__surftimeconst_4o0/parameters.h"
#include "param/init/objects/surfer__us_1o5__surftimeconst_5o0/parameters.h"
#include "param/init/objects/surfer__us_1o5__surftimeconst_6o0/parameters.h"
#include "param/init/objects/surfer__us_1o5__surftimeconst_7o0/parameters.h"
#include "param/init/objects/surfer__us_1o5__surftimeconst_8o0/parameters.h"
#include "param/init/objects/surfer__us_1o5__surftimeconst_9o0/parameters.h"
#include "param/init/objects/surfer__us_1o5__surftimeconst_10o0/parameters.h"
#include "param/init/objects/surfer__us_20o0__surftimeconst_0o0/parameters.h"
#include "param/init/objects/surfer__us_20o0__surftimeconst_2o0/parameters.h"
#include "param/init/objects/surfer__us_20o0__surftimeconst_3o0/parameters.h"
#include "param/init/objects/surfer__us_20o0__surftimeconst_4o0/parameters.h"
#include "param/init/objects/surfer__us_20o0__surftimeconst_5o0/parameters.h"
#include "param/init/objects/surfer__us_20o0__surftimeconst_6o0/parameters.h"
#include "param/init/objects/surfer__us_20o0__surftimeconst_7o0/parameters.h"
#include "param/init/objects/surfer__us_20o0__surftimeconst_8o0/parameters.h"
#include "param/init/objects/surfer__us_20o0__surftimeconst_9o0/parameters.h"
#include "param/init/objects/surfer__us_20o0__surftimeconst_10o0/parameters.h"
#include "param/init/objects/surfer__us_2o0__surftimeconst_0o0/parameters.h"
#include "param/init/objects/surfer__us_2o0__surftimeconst_2o0/parameters.h"
#include "param/init/objects/surfer__us_2o0__surftimeconst_3o0/parameters.h"
#include "param/init/objects/surfer__us_2o0__surftimeconst_4o0/parameters.h"
#include "param/init/objects/surfer__us_2o0__surftimeconst_5o0/parameters.h"
#include "param/init/objects/surfer__us_2o0__surftimeconst_6o0/parameters.h"
#include "param/init/objects/surfer__us_2o0__surftimeconst_7o0/parameters.h"
#include "param/init/objects/surfer__us_2o0__surftimeconst_8o0/parameters.h"
#include "param/init/objects/surfer__us_2o0__surftimeconst_9o0/parameters.h"
#include "param/init/objects/surfer__us_2o0__surftimeconst_10o0/parameters.h"
#include "param/init/objects/surfer__us_2o5__surftimeconst_0o0/parameters.h"
#include "param/init/objects/surfer__us_2o5__surftimeconst_2o0/parameters.h"
#include "param/init/objects/surfer__us_2o5__surftimeconst_3o0/parameters.h"
#include "param/init/objects/surfer__us_2o5__surftimeconst_4o0/parameters.h"
#include "param/init/objects/surfer__us_2o5__surftimeconst_5o0/parameters.h"
#include "param/init/objects/surfer__us_2o5__surftimeconst_6o0/parameters.h"
#include "param/init/objects/surfer__us_2o5__surftimeconst_7o0/parameters.h"
#include "param/init/objects/surfer__us_2o5__surftimeconst_8o0/parameters.h"
#include "param/init/objects/surfer__us_2o5__surftimeconst_9o0/parameters.h"
#include "param/init/objects/surfer__us_2o5__surftimeconst_10o0/parameters.h"
#include "param/init/objects/surfer__us_3o0__surftimeconst_0o0/parameters.h"
#include "param/init/objects/surfer__us_3o0__surftimeconst_2o0/parameters.h"
#include "param/init/objects/surfer__us_3o0__surftimeconst_3o0/parameters.h"
#include "param/init/objects/surfer__us_3o0__surftimeconst_4o0/parameters.h"
#include "param/init/objects/surfer__us_3o0__surftimeconst_5o0/parameters.h"
#include "param/init/objects/surfer__us_3o0__surftimeconst_6o0/parameters.h"
#include "param/init/objects/surfer__us_3o0__surftimeconst_7o0/parameters.h"
#include "param/init/objects/surfer__us_3o0__surftimeconst_8o0/parameters.h"
#include "param/init/objects/surfer__us_3o0__surftimeconst_9o0/parameters.h"
#include "param/init/objects/surfer__us_3o0__surftimeconst_10o0/parameters.h"
#include "param/init/objects/surfer__us_3o5__surftimeconst_0o0/parameters.h"
#include "param/init/objects/surfer__us_3o5__surftimeconst_2o0/parameters.h"
#include "param/init/objects/surfer__us_3o5__surftimeconst_3o0/parameters.h"
#include "param/init/objects/surfer__us_3o5__surftimeconst_4o0/parameters.h"
#include "param/init/objects/surfer__us_3o5__surftimeconst_5o0/parameters.h"
#include "param/init/objects/surfer__us_3o5__surftimeconst_6o0/parameters.h"
#include "param/init/objects/surfer__us_3o5__surftimeconst_7o0/parameters.h"
#include "param/init/objects/surfer__us_3o5__surftimeconst_8o0/parameters.h"
#include "param/init/objects/surfer__us_3o5__surftimeconst_9o0/parameters.h"
#include "param/init/objects/surfer__us_3o5__surftimeconst_10o0/parameters.h"
#include "param/init/objects/surfer__us_4o0__surftimeconst_0o0/parameters.h"
#include "param/init/objects/surfer__us_4o0__surftimeconst_2o0/parameters.h"
#include "param/init/objects/surfer__us_4o0__surftimeconst_3o0/parameters.h"
#include "param/init/objects/surfer__us_4o0__surftimeconst_4o0/parameters.h"
#include "param/init/objects/surfer__us_4o0__surftimeconst_5o0/parameters.h"
#include "param/init/objects/surfer__us_4o0__surftimeconst_6o0/parameters.h"
#include "param/init/objects/surfer__us_4o0__surftimeconst_7o0/parameters.h"
#include "param/init/objects/surfer__us_4o0__surftimeconst_8o0/parameters.h"
#include "param/init/objects/surfer__us_4o0__surftimeconst_9o0/parameters.h"
#include "param/init/objects/surfer__us_4o0__surftimeconst_10o0/parameters.h"
#include "param/init/objects/surfer__us_4o5__surftimeconst_0o0/parameters.h"
#include "param/init/objects/surfer__us_4o5__surftimeconst_2o0/parameters.h"
#include "param/init/objects/surfer__us_4o5__surftimeconst_3o0/parameters.h"
#include "param/init/objects/surfer__us_4o5__surftimeconst_4o0/parameters.h"
#include "param/init/objects/surfer__us_4o5__surftimeconst_5o0/parameters.h"
#include "param/init/objects/surfer__us_4o5__surftimeconst_6o0/parameters.h"
#include "param/init/objects/surfer__us_4o5__surftimeconst_7o0/parameters.h"
#include "param/init/objects/surfer__us_4o5__surftimeconst_8o0/parameters.h"
#include "param/init/objects/surfer__us_4o5__surftimeconst_9o0/parameters.h"
#include "param/init/objects/surfer__us_4o5__surftimeconst_10o0/parameters.h"
#include "param/init/objects/surfer__us_5o0__surftimeconst_0o0/parameters.h"
#include "param/init/objects/surfer__us_5o0__surftimeconst_2o0/parameters.h"
#include "param/init/objects/surfer__us_5o0__surftimeconst_3o0/parameters.h"
#include "param/init/objects/surfer__us_5o0__surftimeconst_4o0/parameters.h"
#include "param/init/objects/surfer__us_5o0__surftimeconst_5o0/parameters.h"
#include "param/init/objects/surfer__us_5o0__surftimeconst_6o0/parameters.h"
#include "param/init/objects/surfer__us_5o0__surftimeconst_7o0/parameters.h"
#include "param/init/objects/surfer__us_5o0__surftimeconst_8o0/parameters.h"
#include "param/init/objects/surfer__us_5o0__surftimeconst_9o0/parameters.h"
#include "param/init/objects/surfer__us_5o0__surftimeconst_10o0/parameters.h"
#include "param/init/objects/surfer__us_6o0__surftimeconst_0o0/parameters.h"
#include "param/init/objects/surfer__us_6o0__surftimeconst_2o0/parameters.h"
#include "param/init/objects/surfer__us_6o0__surftimeconst_3o0/parameters.h"
#include "param/init/objects/surfer__us_6o0__surftimeconst_4o0/parameters.h"
#include "param/init/objects/surfer__us_6o0__surftimeconst_5o0/parameters.h"
#include "param/init/objects/surfer__us_6o0__surftimeconst_6o0/parameters.h"
#include "param/init/objects/surfer__us_6o0__surftimeconst_7o0/parameters.h"
#include "param/init/objects/surfer__us_6o0__surftimeconst_8o0/parameters.h"
#include "param/init/objects/surfer__us_6o0__surftimeconst_9o0/parameters.h"
#include "param/init/objects/surfer__us_6o0__surftimeconst_10o0/parameters.h"
#include "param/init/objects/surfer__us_7o0__surftimeconst_0o0/parameters.h"
#include "param/init/objects/surfer__us_7o0__surftimeconst_2o0/parameters.h"
#include "param/init/objects/surfer__us_7o0__surftimeconst_3o0/parameters.h"
#include "param/init/objects/surfer__us_7o0__surftimeconst_4o0/parameters.h"
#include "param/init/objects/surfer__us_7o0__surftimeconst_5o0/parameters.h"
#include "param/init/objects/surfer__us_7o0__surftimeconst_6o0/parameters.h"
#include "param/init/objects/surfer__us_7o0__surftimeconst_7o0/parameters.h"
#include "param/init/objects/surfer__us_7o0__surftimeconst_8o0/parameters.h"
#include "param/init/objects/surfer__us_7o0__surftimeconst_9o0/parameters.h"
#include "param/init/objects/surfer__us_7o0__surftimeconst_10o0/parameters.h"
#include "param/init/objects/surfer__us_8o0__surftimeconst_0o0/parameters.h"
#include "param/init/objects/surfer__us_8o0__surftimeconst_2o0/parameters.h"
#include "param/init/objects/surfer__us_8o0__surftimeconst_3o0/parameters.h"
#include "param/init/objects/surfer__us_8o0__surftimeconst_4o0/parameters.h"
#include "param/init/objects/surfer__us_8o0__surftimeconst_5o0/parameters.h"
#include "param/init/objects/surfer__us_8o0__surftimeconst_6o0/parameters.h"
#include "param/init/objects/surfer__us_8o0__surftimeconst_7o0/parameters.h"
#include "param/init/objects/surfer__us_8o0__surftimeconst_8o0/parameters.h"
#include "param/init/objects/surfer__us_8o0__surftimeconst_9o0/parameters.h"
#include "param/init/objects/surfer__us_8o0__surftimeconst_10o0/parameters.h"
#include "param/init/objects/surfer__us_9o0__surftimeconst_0o0/parameters.h"
#include "param/init/objects/surfer__us_9o0__surftimeconst_2o0/parameters.h"
#include "param/init/objects/surfer__us_9o0__surftimeconst_3o0/parameters.h"
#include "param/init/objects/surfer__us_9o0__surftimeconst_4o0/parameters.h"
#include "param/init/objects/surfer__us_9o0__surftimeconst_5o0/parameters.h"
#include "param/init/objects/surfer__us_9o0__surftimeconst_6o0/parameters.h"
#include "param/init/objects/surfer__us_9o0__surftimeconst_7o0/parameters.h"
#include "param/init/objects/surfer__us_9o0__surftimeconst_8o0/parameters.h"
#include "param/init/objects/surfer__us_9o0__surftimeconst_9o0/parameters.h"
#include "param/init/objects/surfer__us_9o0__surftimeconst_10o0/parameters.h"
// FLAG: INCLUDE OBJECT END

namespace c0p {

struct InitObjectsParameters {
    // make data
    std::vector<std::shared_ptr<InitInitBase>> data;
    InitObjectsParameters(const TypeObjects& objects) {
        // FLAG: MAKE OBJECT BEGIN
        data.push_back(std::make_shared<InitInit<InitSurferUs1O0Surftimeconst1O0Parameters, SurferUs1O0Surftimeconst1O0Step>>(objects.parameters.sSurferUs1O0Surftimeconst1O0Step));
        data.push_back(std::make_shared<InitInit<InitRiserUs1O0Parameters, RiserUs1O0Step>>(objects.parameters.sRiserUs1O0Step));
        data.push_back(std::make_shared<InitInit<InitRiserUs0O5Parameters, RiserUs0O5Step>>(objects.parameters.sRiserUs0O5Step));
        data.push_back(std::make_shared<InitInit<InitRiserUs1O5Parameters, RiserUs1O5Step>>(objects.parameters.sRiserUs1O5Step));
        data.push_back(std::make_shared<InitInit<InitRiserUs2O0Parameters, RiserUs2O0Step>>(objects.parameters.sRiserUs2O0Step));
        data.push_back(std::make_shared<InitInit<InitRiserUs2O5Parameters, RiserUs2O5Step>>(objects.parameters.sRiserUs2O5Step));
        data.push_back(std::make_shared<InitInit<InitRiserUs3O0Parameters, RiserUs3O0Step>>(objects.parameters.sRiserUs3O0Step));
        data.push_back(std::make_shared<InitInit<InitRiserUs3O5Parameters, RiserUs3O5Step>>(objects.parameters.sRiserUs3O5Step));
        data.push_back(std::make_shared<InitInit<InitRiserUs4O0Parameters, RiserUs4O0Step>>(objects.parameters.sRiserUs4O0Step));
        data.push_back(std::make_shared<InitInit<InitRiserUs4O5Parameters, RiserUs4O5Step>>(objects.parameters.sRiserUs4O5Step));
        data.push_back(std::make_shared<InitInit<InitRiserUs5O0Parameters, RiserUs5O0Step>>(objects.parameters.sRiserUs5O0Step));
        data.push_back(std::make_shared<InitInit<InitRiserUs6O0Parameters, RiserUs6O0Step>>(objects.parameters.sRiserUs6O0Step));
        data.push_back(std::make_shared<InitInit<InitRiserUs7O0Parameters, RiserUs7O0Step>>(objects.parameters.sRiserUs7O0Step));
        data.push_back(std::make_shared<InitInit<InitRiserUs8O0Parameters, RiserUs8O0Step>>(objects.parameters.sRiserUs8O0Step));
        data.push_back(std::make_shared<InitInit<InitRiserUs9O0Parameters, RiserUs9O0Step>>(objects.parameters.sRiserUs9O0Step));
        data.push_back(std::make_shared<InitInit<InitRiserUs10O0Parameters, RiserUs10O0Step>>(objects.parameters.sRiserUs10O0Step));
        data.push_back(std::make_shared<InitInit<InitRiserUs15O0Parameters, RiserUs15O0Step>>(objects.parameters.sRiserUs15O0Step));
        data.push_back(std::make_shared<InitInit<InitRiserUs20O0Parameters, RiserUs20O0Step>>(objects.parameters.sRiserUs20O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs0O5Surftimeconst1O0Parameters, SurferUs0O5Surftimeconst1O0Step>>(objects.parameters.sSurferUs0O5Surftimeconst1O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O5Surftimeconst1O0Parameters, SurferUs1O5Surftimeconst1O0Step>>(objects.parameters.sSurferUs1O5Surftimeconst1O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O0Surftimeconst1O0Parameters, SurferUs2O0Surftimeconst1O0Step>>(objects.parameters.sSurferUs2O0Surftimeconst1O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O5Surftimeconst1O0Parameters, SurferUs2O5Surftimeconst1O0Step>>(objects.parameters.sSurferUs2O5Surftimeconst1O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O0Surftimeconst1O0Parameters, SurferUs3O0Surftimeconst1O0Step>>(objects.parameters.sSurferUs3O0Surftimeconst1O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O5Surftimeconst1O0Parameters, SurferUs3O5Surftimeconst1O0Step>>(objects.parameters.sSurferUs3O5Surftimeconst1O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O0Surftimeconst1O0Parameters, SurferUs4O0Surftimeconst1O0Step>>(objects.parameters.sSurferUs4O0Surftimeconst1O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O5Surftimeconst1O0Parameters, SurferUs4O5Surftimeconst1O0Step>>(objects.parameters.sSurferUs4O5Surftimeconst1O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs5O0Surftimeconst1O0Parameters, SurferUs5O0Surftimeconst1O0Step>>(objects.parameters.sSurferUs5O0Surftimeconst1O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs6O0Surftimeconst1O0Parameters, SurferUs6O0Surftimeconst1O0Step>>(objects.parameters.sSurferUs6O0Surftimeconst1O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs7O0Surftimeconst1O0Parameters, SurferUs7O0Surftimeconst1O0Step>>(objects.parameters.sSurferUs7O0Surftimeconst1O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs8O0Surftimeconst1O0Parameters, SurferUs8O0Surftimeconst1O0Step>>(objects.parameters.sSurferUs8O0Surftimeconst1O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs9O0Surftimeconst1O0Parameters, SurferUs9O0Surftimeconst1O0Step>>(objects.parameters.sSurferUs9O0Surftimeconst1O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs10O0Surftimeconst1O0Parameters, SurferUs10O0Surftimeconst1O0Step>>(objects.parameters.sSurferUs10O0Surftimeconst1O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs15O0Surftimeconst1O0Parameters, SurferUs15O0Surftimeconst1O0Step>>(objects.parameters.sSurferUs15O0Surftimeconst1O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs20O0Surftimeconst1O0Parameters, SurferUs20O0Surftimeconst1O0Step>>(objects.parameters.sSurferUs20O0Surftimeconst1O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs0O5Surftimeconst0O0Parameters, SurferUs0O5Surftimeconst0O0Step>>(objects.parameters.sSurferUs0O5Surftimeconst0O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs0O5Surftimeconst2O0Parameters, SurferUs0O5Surftimeconst2O0Step>>(objects.parameters.sSurferUs0O5Surftimeconst2O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs0O5Surftimeconst3O0Parameters, SurferUs0O5Surftimeconst3O0Step>>(objects.parameters.sSurferUs0O5Surftimeconst3O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs0O5Surftimeconst4O0Parameters, SurferUs0O5Surftimeconst4O0Step>>(objects.parameters.sSurferUs0O5Surftimeconst4O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs0O5Surftimeconst5O0Parameters, SurferUs0O5Surftimeconst5O0Step>>(objects.parameters.sSurferUs0O5Surftimeconst5O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs0O5Surftimeconst6O0Parameters, SurferUs0O5Surftimeconst6O0Step>>(objects.parameters.sSurferUs0O5Surftimeconst6O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs0O5Surftimeconst7O0Parameters, SurferUs0O5Surftimeconst7O0Step>>(objects.parameters.sSurferUs0O5Surftimeconst7O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs0O5Surftimeconst8O0Parameters, SurferUs0O5Surftimeconst8O0Step>>(objects.parameters.sSurferUs0O5Surftimeconst8O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs0O5Surftimeconst9O0Parameters, SurferUs0O5Surftimeconst9O0Step>>(objects.parameters.sSurferUs0O5Surftimeconst9O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs0O5Surftimeconst10O0Parameters, SurferUs0O5Surftimeconst10O0Step>>(objects.parameters.sSurferUs0O5Surftimeconst10O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs10O0Surftimeconst0O0Parameters, SurferUs10O0Surftimeconst0O0Step>>(objects.parameters.sSurferUs10O0Surftimeconst0O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs10O0Surftimeconst2O0Parameters, SurferUs10O0Surftimeconst2O0Step>>(objects.parameters.sSurferUs10O0Surftimeconst2O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs10O0Surftimeconst3O0Parameters, SurferUs10O0Surftimeconst3O0Step>>(objects.parameters.sSurferUs10O0Surftimeconst3O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs10O0Surftimeconst4O0Parameters, SurferUs10O0Surftimeconst4O0Step>>(objects.parameters.sSurferUs10O0Surftimeconst4O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs10O0Surftimeconst5O0Parameters, SurferUs10O0Surftimeconst5O0Step>>(objects.parameters.sSurferUs10O0Surftimeconst5O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs10O0Surftimeconst6O0Parameters, SurferUs10O0Surftimeconst6O0Step>>(objects.parameters.sSurferUs10O0Surftimeconst6O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs10O0Surftimeconst7O0Parameters, SurferUs10O0Surftimeconst7O0Step>>(objects.parameters.sSurferUs10O0Surftimeconst7O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs10O0Surftimeconst8O0Parameters, SurferUs10O0Surftimeconst8O0Step>>(objects.parameters.sSurferUs10O0Surftimeconst8O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs10O0Surftimeconst9O0Parameters, SurferUs10O0Surftimeconst9O0Step>>(objects.parameters.sSurferUs10O0Surftimeconst9O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs10O0Surftimeconst10O0Parameters, SurferUs10O0Surftimeconst10O0Step>>(objects.parameters.sSurferUs10O0Surftimeconst10O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs15O0Surftimeconst0O0Parameters, SurferUs15O0Surftimeconst0O0Step>>(objects.parameters.sSurferUs15O0Surftimeconst0O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs15O0Surftimeconst2O0Parameters, SurferUs15O0Surftimeconst2O0Step>>(objects.parameters.sSurferUs15O0Surftimeconst2O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs15O0Surftimeconst3O0Parameters, SurferUs15O0Surftimeconst3O0Step>>(objects.parameters.sSurferUs15O0Surftimeconst3O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs15O0Surftimeconst4O0Parameters, SurferUs15O0Surftimeconst4O0Step>>(objects.parameters.sSurferUs15O0Surftimeconst4O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs15O0Surftimeconst5O0Parameters, SurferUs15O0Surftimeconst5O0Step>>(objects.parameters.sSurferUs15O0Surftimeconst5O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs15O0Surftimeconst6O0Parameters, SurferUs15O0Surftimeconst6O0Step>>(objects.parameters.sSurferUs15O0Surftimeconst6O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs15O0Surftimeconst7O0Parameters, SurferUs15O0Surftimeconst7O0Step>>(objects.parameters.sSurferUs15O0Surftimeconst7O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs15O0Surftimeconst8O0Parameters, SurferUs15O0Surftimeconst8O0Step>>(objects.parameters.sSurferUs15O0Surftimeconst8O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs15O0Surftimeconst9O0Parameters, SurferUs15O0Surftimeconst9O0Step>>(objects.parameters.sSurferUs15O0Surftimeconst9O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs15O0Surftimeconst10O0Parameters, SurferUs15O0Surftimeconst10O0Step>>(objects.parameters.sSurferUs15O0Surftimeconst10O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O0Surftimeconst0O0Parameters, SurferUs1O0Surftimeconst0O0Step>>(objects.parameters.sSurferUs1O0Surftimeconst0O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O0Surftimeconst2O0Parameters, SurferUs1O0Surftimeconst2O0Step>>(objects.parameters.sSurferUs1O0Surftimeconst2O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O0Surftimeconst3O0Parameters, SurferUs1O0Surftimeconst3O0Step>>(objects.parameters.sSurferUs1O0Surftimeconst3O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O0Surftimeconst4O0Parameters, SurferUs1O0Surftimeconst4O0Step>>(objects.parameters.sSurferUs1O0Surftimeconst4O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O0Surftimeconst5O0Parameters, SurferUs1O0Surftimeconst5O0Step>>(objects.parameters.sSurferUs1O0Surftimeconst5O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O0Surftimeconst6O0Parameters, SurferUs1O0Surftimeconst6O0Step>>(objects.parameters.sSurferUs1O0Surftimeconst6O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O0Surftimeconst7O0Parameters, SurferUs1O0Surftimeconst7O0Step>>(objects.parameters.sSurferUs1O0Surftimeconst7O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O0Surftimeconst8O0Parameters, SurferUs1O0Surftimeconst8O0Step>>(objects.parameters.sSurferUs1O0Surftimeconst8O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O0Surftimeconst9O0Parameters, SurferUs1O0Surftimeconst9O0Step>>(objects.parameters.sSurferUs1O0Surftimeconst9O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O0Surftimeconst10O0Parameters, SurferUs1O0Surftimeconst10O0Step>>(objects.parameters.sSurferUs1O0Surftimeconst10O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O5Surftimeconst0O0Parameters, SurferUs1O5Surftimeconst0O0Step>>(objects.parameters.sSurferUs1O5Surftimeconst0O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O5Surftimeconst2O0Parameters, SurferUs1O5Surftimeconst2O0Step>>(objects.parameters.sSurferUs1O5Surftimeconst2O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O5Surftimeconst3O0Parameters, SurferUs1O5Surftimeconst3O0Step>>(objects.parameters.sSurferUs1O5Surftimeconst3O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O5Surftimeconst4O0Parameters, SurferUs1O5Surftimeconst4O0Step>>(objects.parameters.sSurferUs1O5Surftimeconst4O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O5Surftimeconst5O0Parameters, SurferUs1O5Surftimeconst5O0Step>>(objects.parameters.sSurferUs1O5Surftimeconst5O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O5Surftimeconst6O0Parameters, SurferUs1O5Surftimeconst6O0Step>>(objects.parameters.sSurferUs1O5Surftimeconst6O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O5Surftimeconst7O0Parameters, SurferUs1O5Surftimeconst7O0Step>>(objects.parameters.sSurferUs1O5Surftimeconst7O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O5Surftimeconst8O0Parameters, SurferUs1O5Surftimeconst8O0Step>>(objects.parameters.sSurferUs1O5Surftimeconst8O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O5Surftimeconst9O0Parameters, SurferUs1O5Surftimeconst9O0Step>>(objects.parameters.sSurferUs1O5Surftimeconst9O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs1O5Surftimeconst10O0Parameters, SurferUs1O5Surftimeconst10O0Step>>(objects.parameters.sSurferUs1O5Surftimeconst10O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs20O0Surftimeconst0O0Parameters, SurferUs20O0Surftimeconst0O0Step>>(objects.parameters.sSurferUs20O0Surftimeconst0O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs20O0Surftimeconst2O0Parameters, SurferUs20O0Surftimeconst2O0Step>>(objects.parameters.sSurferUs20O0Surftimeconst2O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs20O0Surftimeconst3O0Parameters, SurferUs20O0Surftimeconst3O0Step>>(objects.parameters.sSurferUs20O0Surftimeconst3O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs20O0Surftimeconst4O0Parameters, SurferUs20O0Surftimeconst4O0Step>>(objects.parameters.sSurferUs20O0Surftimeconst4O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs20O0Surftimeconst5O0Parameters, SurferUs20O0Surftimeconst5O0Step>>(objects.parameters.sSurferUs20O0Surftimeconst5O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs20O0Surftimeconst6O0Parameters, SurferUs20O0Surftimeconst6O0Step>>(objects.parameters.sSurferUs20O0Surftimeconst6O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs20O0Surftimeconst7O0Parameters, SurferUs20O0Surftimeconst7O0Step>>(objects.parameters.sSurferUs20O0Surftimeconst7O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs20O0Surftimeconst8O0Parameters, SurferUs20O0Surftimeconst8O0Step>>(objects.parameters.sSurferUs20O0Surftimeconst8O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs20O0Surftimeconst9O0Parameters, SurferUs20O0Surftimeconst9O0Step>>(objects.parameters.sSurferUs20O0Surftimeconst9O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs20O0Surftimeconst10O0Parameters, SurferUs20O0Surftimeconst10O0Step>>(objects.parameters.sSurferUs20O0Surftimeconst10O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O0Surftimeconst0O0Parameters, SurferUs2O0Surftimeconst0O0Step>>(objects.parameters.sSurferUs2O0Surftimeconst0O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O0Surftimeconst2O0Parameters, SurferUs2O0Surftimeconst2O0Step>>(objects.parameters.sSurferUs2O0Surftimeconst2O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O0Surftimeconst3O0Parameters, SurferUs2O0Surftimeconst3O0Step>>(objects.parameters.sSurferUs2O0Surftimeconst3O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O0Surftimeconst4O0Parameters, SurferUs2O0Surftimeconst4O0Step>>(objects.parameters.sSurferUs2O0Surftimeconst4O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O0Surftimeconst5O0Parameters, SurferUs2O0Surftimeconst5O0Step>>(objects.parameters.sSurferUs2O0Surftimeconst5O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O0Surftimeconst6O0Parameters, SurferUs2O0Surftimeconst6O0Step>>(objects.parameters.sSurferUs2O0Surftimeconst6O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O0Surftimeconst7O0Parameters, SurferUs2O0Surftimeconst7O0Step>>(objects.parameters.sSurferUs2O0Surftimeconst7O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O0Surftimeconst8O0Parameters, SurferUs2O0Surftimeconst8O0Step>>(objects.parameters.sSurferUs2O0Surftimeconst8O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O0Surftimeconst9O0Parameters, SurferUs2O0Surftimeconst9O0Step>>(objects.parameters.sSurferUs2O0Surftimeconst9O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O0Surftimeconst10O0Parameters, SurferUs2O0Surftimeconst10O0Step>>(objects.parameters.sSurferUs2O0Surftimeconst10O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O5Surftimeconst0O0Parameters, SurferUs2O5Surftimeconst0O0Step>>(objects.parameters.sSurferUs2O5Surftimeconst0O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O5Surftimeconst2O0Parameters, SurferUs2O5Surftimeconst2O0Step>>(objects.parameters.sSurferUs2O5Surftimeconst2O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O5Surftimeconst3O0Parameters, SurferUs2O5Surftimeconst3O0Step>>(objects.parameters.sSurferUs2O5Surftimeconst3O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O5Surftimeconst4O0Parameters, SurferUs2O5Surftimeconst4O0Step>>(objects.parameters.sSurferUs2O5Surftimeconst4O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O5Surftimeconst5O0Parameters, SurferUs2O5Surftimeconst5O0Step>>(objects.parameters.sSurferUs2O5Surftimeconst5O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O5Surftimeconst6O0Parameters, SurferUs2O5Surftimeconst6O0Step>>(objects.parameters.sSurferUs2O5Surftimeconst6O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O5Surftimeconst7O0Parameters, SurferUs2O5Surftimeconst7O0Step>>(objects.parameters.sSurferUs2O5Surftimeconst7O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O5Surftimeconst8O0Parameters, SurferUs2O5Surftimeconst8O0Step>>(objects.parameters.sSurferUs2O5Surftimeconst8O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O5Surftimeconst9O0Parameters, SurferUs2O5Surftimeconst9O0Step>>(objects.parameters.sSurferUs2O5Surftimeconst9O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs2O5Surftimeconst10O0Parameters, SurferUs2O5Surftimeconst10O0Step>>(objects.parameters.sSurferUs2O5Surftimeconst10O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O0Surftimeconst0O0Parameters, SurferUs3O0Surftimeconst0O0Step>>(objects.parameters.sSurferUs3O0Surftimeconst0O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O0Surftimeconst2O0Parameters, SurferUs3O0Surftimeconst2O0Step>>(objects.parameters.sSurferUs3O0Surftimeconst2O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O0Surftimeconst3O0Parameters, SurferUs3O0Surftimeconst3O0Step>>(objects.parameters.sSurferUs3O0Surftimeconst3O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O0Surftimeconst4O0Parameters, SurferUs3O0Surftimeconst4O0Step>>(objects.parameters.sSurferUs3O0Surftimeconst4O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O0Surftimeconst5O0Parameters, SurferUs3O0Surftimeconst5O0Step>>(objects.parameters.sSurferUs3O0Surftimeconst5O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O0Surftimeconst6O0Parameters, SurferUs3O0Surftimeconst6O0Step>>(objects.parameters.sSurferUs3O0Surftimeconst6O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O0Surftimeconst7O0Parameters, SurferUs3O0Surftimeconst7O0Step>>(objects.parameters.sSurferUs3O0Surftimeconst7O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O0Surftimeconst8O0Parameters, SurferUs3O0Surftimeconst8O0Step>>(objects.parameters.sSurferUs3O0Surftimeconst8O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O0Surftimeconst9O0Parameters, SurferUs3O0Surftimeconst9O0Step>>(objects.parameters.sSurferUs3O0Surftimeconst9O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O0Surftimeconst10O0Parameters, SurferUs3O0Surftimeconst10O0Step>>(objects.parameters.sSurferUs3O0Surftimeconst10O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O5Surftimeconst0O0Parameters, SurferUs3O5Surftimeconst0O0Step>>(objects.parameters.sSurferUs3O5Surftimeconst0O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O5Surftimeconst2O0Parameters, SurferUs3O5Surftimeconst2O0Step>>(objects.parameters.sSurferUs3O5Surftimeconst2O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O5Surftimeconst3O0Parameters, SurferUs3O5Surftimeconst3O0Step>>(objects.parameters.sSurferUs3O5Surftimeconst3O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O5Surftimeconst4O0Parameters, SurferUs3O5Surftimeconst4O0Step>>(objects.parameters.sSurferUs3O5Surftimeconst4O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O5Surftimeconst5O0Parameters, SurferUs3O5Surftimeconst5O0Step>>(objects.parameters.sSurferUs3O5Surftimeconst5O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O5Surftimeconst6O0Parameters, SurferUs3O5Surftimeconst6O0Step>>(objects.parameters.sSurferUs3O5Surftimeconst6O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O5Surftimeconst7O0Parameters, SurferUs3O5Surftimeconst7O0Step>>(objects.parameters.sSurferUs3O5Surftimeconst7O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O5Surftimeconst8O0Parameters, SurferUs3O5Surftimeconst8O0Step>>(objects.parameters.sSurferUs3O5Surftimeconst8O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O5Surftimeconst9O0Parameters, SurferUs3O5Surftimeconst9O0Step>>(objects.parameters.sSurferUs3O5Surftimeconst9O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs3O5Surftimeconst10O0Parameters, SurferUs3O5Surftimeconst10O0Step>>(objects.parameters.sSurferUs3O5Surftimeconst10O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O0Surftimeconst0O0Parameters, SurferUs4O0Surftimeconst0O0Step>>(objects.parameters.sSurferUs4O0Surftimeconst0O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O0Surftimeconst2O0Parameters, SurferUs4O0Surftimeconst2O0Step>>(objects.parameters.sSurferUs4O0Surftimeconst2O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O0Surftimeconst3O0Parameters, SurferUs4O0Surftimeconst3O0Step>>(objects.parameters.sSurferUs4O0Surftimeconst3O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O0Surftimeconst4O0Parameters, SurferUs4O0Surftimeconst4O0Step>>(objects.parameters.sSurferUs4O0Surftimeconst4O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O0Surftimeconst5O0Parameters, SurferUs4O0Surftimeconst5O0Step>>(objects.parameters.sSurferUs4O0Surftimeconst5O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O0Surftimeconst6O0Parameters, SurferUs4O0Surftimeconst6O0Step>>(objects.parameters.sSurferUs4O0Surftimeconst6O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O0Surftimeconst7O0Parameters, SurferUs4O0Surftimeconst7O0Step>>(objects.parameters.sSurferUs4O0Surftimeconst7O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O0Surftimeconst8O0Parameters, SurferUs4O0Surftimeconst8O0Step>>(objects.parameters.sSurferUs4O0Surftimeconst8O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O0Surftimeconst9O0Parameters, SurferUs4O0Surftimeconst9O0Step>>(objects.parameters.sSurferUs4O0Surftimeconst9O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O0Surftimeconst10O0Parameters, SurferUs4O0Surftimeconst10O0Step>>(objects.parameters.sSurferUs4O0Surftimeconst10O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O5Surftimeconst0O0Parameters, SurferUs4O5Surftimeconst0O0Step>>(objects.parameters.sSurferUs4O5Surftimeconst0O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O5Surftimeconst2O0Parameters, SurferUs4O5Surftimeconst2O0Step>>(objects.parameters.sSurferUs4O5Surftimeconst2O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O5Surftimeconst3O0Parameters, SurferUs4O5Surftimeconst3O0Step>>(objects.parameters.sSurferUs4O5Surftimeconst3O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O5Surftimeconst4O0Parameters, SurferUs4O5Surftimeconst4O0Step>>(objects.parameters.sSurferUs4O5Surftimeconst4O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O5Surftimeconst5O0Parameters, SurferUs4O5Surftimeconst5O0Step>>(objects.parameters.sSurferUs4O5Surftimeconst5O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O5Surftimeconst6O0Parameters, SurferUs4O5Surftimeconst6O0Step>>(objects.parameters.sSurferUs4O5Surftimeconst6O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O5Surftimeconst7O0Parameters, SurferUs4O5Surftimeconst7O0Step>>(objects.parameters.sSurferUs4O5Surftimeconst7O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O5Surftimeconst8O0Parameters, SurferUs4O5Surftimeconst8O0Step>>(objects.parameters.sSurferUs4O5Surftimeconst8O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O5Surftimeconst9O0Parameters, SurferUs4O5Surftimeconst9O0Step>>(objects.parameters.sSurferUs4O5Surftimeconst9O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs4O5Surftimeconst10O0Parameters, SurferUs4O5Surftimeconst10O0Step>>(objects.parameters.sSurferUs4O5Surftimeconst10O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs5O0Surftimeconst0O0Parameters, SurferUs5O0Surftimeconst0O0Step>>(objects.parameters.sSurferUs5O0Surftimeconst0O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs5O0Surftimeconst2O0Parameters, SurferUs5O0Surftimeconst2O0Step>>(objects.parameters.sSurferUs5O0Surftimeconst2O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs5O0Surftimeconst3O0Parameters, SurferUs5O0Surftimeconst3O0Step>>(objects.parameters.sSurferUs5O0Surftimeconst3O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs5O0Surftimeconst4O0Parameters, SurferUs5O0Surftimeconst4O0Step>>(objects.parameters.sSurferUs5O0Surftimeconst4O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs5O0Surftimeconst5O0Parameters, SurferUs5O0Surftimeconst5O0Step>>(objects.parameters.sSurferUs5O0Surftimeconst5O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs5O0Surftimeconst6O0Parameters, SurferUs5O0Surftimeconst6O0Step>>(objects.parameters.sSurferUs5O0Surftimeconst6O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs5O0Surftimeconst7O0Parameters, SurferUs5O0Surftimeconst7O0Step>>(objects.parameters.sSurferUs5O0Surftimeconst7O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs5O0Surftimeconst8O0Parameters, SurferUs5O0Surftimeconst8O0Step>>(objects.parameters.sSurferUs5O0Surftimeconst8O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs5O0Surftimeconst9O0Parameters, SurferUs5O0Surftimeconst9O0Step>>(objects.parameters.sSurferUs5O0Surftimeconst9O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs5O0Surftimeconst10O0Parameters, SurferUs5O0Surftimeconst10O0Step>>(objects.parameters.sSurferUs5O0Surftimeconst10O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs6O0Surftimeconst0O0Parameters, SurferUs6O0Surftimeconst0O0Step>>(objects.parameters.sSurferUs6O0Surftimeconst0O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs6O0Surftimeconst2O0Parameters, SurferUs6O0Surftimeconst2O0Step>>(objects.parameters.sSurferUs6O0Surftimeconst2O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs6O0Surftimeconst3O0Parameters, SurferUs6O0Surftimeconst3O0Step>>(objects.parameters.sSurferUs6O0Surftimeconst3O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs6O0Surftimeconst4O0Parameters, SurferUs6O0Surftimeconst4O0Step>>(objects.parameters.sSurferUs6O0Surftimeconst4O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs6O0Surftimeconst5O0Parameters, SurferUs6O0Surftimeconst5O0Step>>(objects.parameters.sSurferUs6O0Surftimeconst5O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs6O0Surftimeconst6O0Parameters, SurferUs6O0Surftimeconst6O0Step>>(objects.parameters.sSurferUs6O0Surftimeconst6O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs6O0Surftimeconst7O0Parameters, SurferUs6O0Surftimeconst7O0Step>>(objects.parameters.sSurferUs6O0Surftimeconst7O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs6O0Surftimeconst8O0Parameters, SurferUs6O0Surftimeconst8O0Step>>(objects.parameters.sSurferUs6O0Surftimeconst8O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs6O0Surftimeconst9O0Parameters, SurferUs6O0Surftimeconst9O0Step>>(objects.parameters.sSurferUs6O0Surftimeconst9O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs6O0Surftimeconst10O0Parameters, SurferUs6O0Surftimeconst10O0Step>>(objects.parameters.sSurferUs6O0Surftimeconst10O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs7O0Surftimeconst0O0Parameters, SurferUs7O0Surftimeconst0O0Step>>(objects.parameters.sSurferUs7O0Surftimeconst0O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs7O0Surftimeconst2O0Parameters, SurferUs7O0Surftimeconst2O0Step>>(objects.parameters.sSurferUs7O0Surftimeconst2O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs7O0Surftimeconst3O0Parameters, SurferUs7O0Surftimeconst3O0Step>>(objects.parameters.sSurferUs7O0Surftimeconst3O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs7O0Surftimeconst4O0Parameters, SurferUs7O0Surftimeconst4O0Step>>(objects.parameters.sSurferUs7O0Surftimeconst4O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs7O0Surftimeconst5O0Parameters, SurferUs7O0Surftimeconst5O0Step>>(objects.parameters.sSurferUs7O0Surftimeconst5O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs7O0Surftimeconst6O0Parameters, SurferUs7O0Surftimeconst6O0Step>>(objects.parameters.sSurferUs7O0Surftimeconst6O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs7O0Surftimeconst7O0Parameters, SurferUs7O0Surftimeconst7O0Step>>(objects.parameters.sSurferUs7O0Surftimeconst7O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs7O0Surftimeconst8O0Parameters, SurferUs7O0Surftimeconst8O0Step>>(objects.parameters.sSurferUs7O0Surftimeconst8O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs7O0Surftimeconst9O0Parameters, SurferUs7O0Surftimeconst9O0Step>>(objects.parameters.sSurferUs7O0Surftimeconst9O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs7O0Surftimeconst10O0Parameters, SurferUs7O0Surftimeconst10O0Step>>(objects.parameters.sSurferUs7O0Surftimeconst10O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs8O0Surftimeconst0O0Parameters, SurferUs8O0Surftimeconst0O0Step>>(objects.parameters.sSurferUs8O0Surftimeconst0O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs8O0Surftimeconst2O0Parameters, SurferUs8O0Surftimeconst2O0Step>>(objects.parameters.sSurferUs8O0Surftimeconst2O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs8O0Surftimeconst3O0Parameters, SurferUs8O0Surftimeconst3O0Step>>(objects.parameters.sSurferUs8O0Surftimeconst3O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs8O0Surftimeconst4O0Parameters, SurferUs8O0Surftimeconst4O0Step>>(objects.parameters.sSurferUs8O0Surftimeconst4O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs8O0Surftimeconst5O0Parameters, SurferUs8O0Surftimeconst5O0Step>>(objects.parameters.sSurferUs8O0Surftimeconst5O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs8O0Surftimeconst6O0Parameters, SurferUs8O0Surftimeconst6O0Step>>(objects.parameters.sSurferUs8O0Surftimeconst6O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs8O0Surftimeconst7O0Parameters, SurferUs8O0Surftimeconst7O0Step>>(objects.parameters.sSurferUs8O0Surftimeconst7O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs8O0Surftimeconst8O0Parameters, SurferUs8O0Surftimeconst8O0Step>>(objects.parameters.sSurferUs8O0Surftimeconst8O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs8O0Surftimeconst9O0Parameters, SurferUs8O0Surftimeconst9O0Step>>(objects.parameters.sSurferUs8O0Surftimeconst9O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs8O0Surftimeconst10O0Parameters, SurferUs8O0Surftimeconst10O0Step>>(objects.parameters.sSurferUs8O0Surftimeconst10O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs9O0Surftimeconst0O0Parameters, SurferUs9O0Surftimeconst0O0Step>>(objects.parameters.sSurferUs9O0Surftimeconst0O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs9O0Surftimeconst2O0Parameters, SurferUs9O0Surftimeconst2O0Step>>(objects.parameters.sSurferUs9O0Surftimeconst2O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs9O0Surftimeconst3O0Parameters, SurferUs9O0Surftimeconst3O0Step>>(objects.parameters.sSurferUs9O0Surftimeconst3O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs9O0Surftimeconst4O0Parameters, SurferUs9O0Surftimeconst4O0Step>>(objects.parameters.sSurferUs9O0Surftimeconst4O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs9O0Surftimeconst5O0Parameters, SurferUs9O0Surftimeconst5O0Step>>(objects.parameters.sSurferUs9O0Surftimeconst5O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs9O0Surftimeconst6O0Parameters, SurferUs9O0Surftimeconst6O0Step>>(objects.parameters.sSurferUs9O0Surftimeconst6O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs9O0Surftimeconst7O0Parameters, SurferUs9O0Surftimeconst7O0Step>>(objects.parameters.sSurferUs9O0Surftimeconst7O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs9O0Surftimeconst8O0Parameters, SurferUs9O0Surftimeconst8O0Step>>(objects.parameters.sSurferUs9O0Surftimeconst8O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs9O0Surftimeconst9O0Parameters, SurferUs9O0Surftimeconst9O0Step>>(objects.parameters.sSurferUs9O0Surftimeconst9O0Step));
        data.push_back(std::make_shared<InitInit<InitSurferUs9O0Surftimeconst10O0Parameters, SurferUs9O0Surftimeconst10O0Step>>(objects.parameters.sSurferUs9O0Surftimeconst10O0Step));
        // FLAG: MAKE OBJECT END
    }
};

}

#endif
