#ifndef C0P_PARAM_POST_OBJECTS_SURFER__US_15O58__SURFTIMECONST_5O0__REORIENTATIONTIME_0O5_PY_GROUP_MEMBER_CHOICE_H
#define C0P_PARAM_POST_OBJECTS_SURFER__US_15O58__SURFTIMECONST_5O0__REORIENTATIONTIME_0O5_PY_GROUP_MEMBER_CHOICE_H
#pragma once

// choose your post
#include "param/post/objects/surfer__us_15o58__surftimeconst_5o0__reorientationtime_0o5/py/group/_member/passive/choice.h"

namespace c0p {
    template<typename TypeMemberStep>
    using PostSurferUs15O58Surftimeconst5O0Reorientationtime0O5PyGroupMember = PostSurferUs15O58Surftimeconst5O0Reorientationtime0O5PyGroupMemberPassive<TypeMemberStep>;
}

#endif
