#ifndef C0P_PARAM_POST_OBJECTS_SURFER__US_15O58__SURFTIMECONST_0O0__REORIENTATIONTIME_0O5_PZ_CHOICE_H
#define C0P_PARAM_POST_OBJECTS_SURFER__US_15O58__SURFTIMECONST_0O0__REORIENTATIONTIME_0O5_PZ_CHOICE_H
#pragma once

// choose your post processing
#include "core/post/objects/object/post/group/all/core.h"
#include "param/post/objects/surfer__us_15o58__surftimeconst_0o0__reorientationtime_0o5/pz/group/all/parameters.h"
namespace c0p {
    template<typename TypeSurferUs15O58Surftimeconst0O0Reorientationtime0O5Step>
    using PostSurferUs15O58Surftimeconst0O0Reorientationtime0O5Pz = PostPostGroupAll<PostSurferUs15O58Surftimeconst0O0Reorientationtime0O5PzGroupAllParameters, TypeSurferUs15O58Surftimeconst0O0Reorientationtime0O5Step>;
}

#endif
