#ifndef C0P_PARAM_POST_OBJECTS_SURFER__US_15O58__SURFTIMECONST_7O0__REORIENTATIONTIME_0O5_PY_GROUP_MEMBER_PASSIVE_CHOICE_H
#define C0P_PARAM_POST_OBJECTS_SURFER__US_15O58__SURFTIMECONST_7O0__REORIENTATIONTIME_0O5_PY_GROUP_MEMBER_PASSIVE_CHOICE_H
#pragma once

// choose your post
#include "core/post/objects/object/post/passive/position/core.h"
#include "param/post/objects/surfer__us_15o58__surftimeconst_7o0__reorientationtime_0o5/py/group/_member/passive/position/parameters.h"

namespace c0p {
    template<typename TypeSurferUs15O58Surftimeconst7O0Reorientationtime0O5Step>
    using PostSurferUs15O58Surftimeconst7O0Reorientationtime0O5PyGroupMemberPassive = PostPostPassivePosition<PostSurferUs15O58Surftimeconst7O0Reorientationtime0O5PyGroupMemberPassivePositionParameters, TypeSurferUs15O58Surftimeconst7O0Reorientationtime0O5Step>;
}

#endif
