#ifndef C0P_PARAM_OBJECTS_OBJECT_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_SWIM_IN_DIRECTION_SWIMMING_DIRECTION_CHOICE_H
#define C0P_PARAM_OBJECTS_OBJECT_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_SWIM_IN_DIRECTION_SWIMMING_DIRECTION_CHOICE_H
#pragma once

// behaviour direction choice
#include "param/env/objects/object/group/homogeneous/_member/agent/_behaviour/swim_in_direction/swimming_direction/_behaviour_direction/choice.h"
// choose your behaviour
#include "core/env/objects/object/agent/behaviour/swim_in_direction/swimming_direction/local_axis_swimmer/core.h"
#include "param/env/objects/object/group/homogeneous/_member/agent/_behaviour/swim_in_direction/swimming_direction/local_axis_swimmer/parameters.h"
namespace c0p {
    template<typename ObjectGroupHomogeneousMemberAgentActiveStep>
    using ObjectGroupHomogeneousMemberAgentBehaviourSwimInDirectionSwimmingDirection = AgentBehaviourSwimInDirectionSwimmingDirectionLocalAxisSwimmer<ObjectGroupHomogeneousMemberAgentBehaviourSwimInDirectionSwimmingDirectionLocalAxisSwimmerParameters, ObjectGroupHomogeneousMemberAgentActiveStep, ObjectGroupHomogeneousMemberAgentBehaviourSwimInDirectionSwimmingDirectionBehaviourDirection<ObjectGroupHomogeneousMemberAgentActiveStep>>;
}

#endif
