#ifndef C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_10O0__REORIENTATIONTIME_1O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CONST_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_10O0__REORIENTATIONTIME_1O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CONST_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// sensor choice
#include "param/env/objects/surfer__us_1o0__surftimeconst_10o0__reorientationtime_1o0/group/homogeneous/_member/agent/_behaviour/_sensor/direction/choice.h"
#include "param/env/objects/surfer__us_1o0__surftimeconst_10o0__reorientationtime_1o0/group/homogeneous/_member/agent/_behaviour/_sensor/velocity_gradients/choice.h"
// choose your behaviour
#include "core/env/objects/object/agent/behaviour/navigator/behaviour_velocity/const/core.h"
#include "param/env/objects/surfer__us_1o0__surftimeconst_10o0__reorientationtime_1o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/parameters.h"
namespace c0p {
    template<typename SurferUs1O0Surftimeconst10O0Reorientationtime1O0GroupHomogeneousMemberAgentActiveStep>
    using SurferUs1O0Surftimeconst10O0Reorientationtime1O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst = AgentBehaviourNavigatorBehaviourVelocityConst<SurferUs1O0Surftimeconst10O0Reorientationtime1O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConstParameters, SurferUs1O0Surftimeconst10O0Reorientationtime1O0GroupHomogeneousMemberAgentActiveStep, SurferUs1O0Surftimeconst10O0Reorientationtime1O0GroupHomogeneousMemberAgentBehaviourSensorDirection<SurferUs1O0Surftimeconst10O0Reorientationtime1O0GroupHomogeneousMemberAgentActiveStep>, SurferUs1O0Surftimeconst10O0Reorientationtime1O0GroupHomogeneousMemberAgentBehaviourSensorVelocityGradients<SurferUs1O0Surftimeconst10O0Reorientationtime1O0GroupHomogeneousMemberAgentActiveStep>>;
}

#endif
