#ifndef C0P_PARAM_OBJECTS_SURFER__US_0O1__SURFTIMECONST_1O25_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_0O1__SURFTIMECONST_1O25_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/static/surfer__us_0o1__surftimeconst_1o25/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/choice.h"
namespace c0p {
    template<typename SurferUs0O1Surftimeconst1O25GroupHomogeneousMemberAgentActiveStep>
    using SurferUs0O1Surftimeconst1O25GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity = SurferUs0O1Surftimeconst1O25GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst<SurferUs0O1Surftimeconst1O25GroupHomogeneousMemberAgentActiveStep>;
}

#endif
