#ifndef C0P_PARAM_OBJECTS_SURFER__US_15O58__SURFTIMECONST_5O0__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_TRACKER_BEHAVIOUR_VELOCITY_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_15O58__SURFTIMECONST_5O0__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_TRACKER_BEHAVIOUR_VELOCITY_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/static/surfer__us_15o58__surftimeconst_5o0__reorientationtime_0o5/group/homogeneous/_member/agent/_behaviour/tracker/_behaviour_velocity/const/choice.h"
namespace c0p {
    template<typename SurferUs15O58Surftimeconst5O0Reorientationtime0O5GroupHomogeneousMemberAgentActiveStep>
    using SurferUs15O58Surftimeconst5O0Reorientationtime0O5GroupHomogeneousMemberAgentBehaviourTrackerBehaviourVelocity = SurferUs15O58Surftimeconst5O0Reorientationtime0O5GroupHomogeneousMemberAgentBehaviourTrackerBehaviourVelocityConst<SurferUs15O58Surftimeconst5O0Reorientationtime0O5GroupHomogeneousMemberAgentActiveStep>;
}

#endif
