#ifndef C0P_PARAM_OBJECTS_SURFER__VS_1O0__SURFTIMECONST_5O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__VS_1O0__SURFTIMECONST_5O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/static/surfer__vs_1o0__surftimeconst_5o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_direction/surf/choice.h"
namespace c0p {
    template<typename SurferVs1O0Surftimeconst5O0GroupHomogeneousMemberAgentActiveStep>
    using SurferVs1O0Surftimeconst5O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirection = SurferVs1O0Surftimeconst5O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirectionSurf<SurferVs1O0Surftimeconst5O0GroupHomogeneousMemberAgentActiveStep>;
}

#endif
