#ifndef C0P_PARAM_OBJECTS_SURFER__US_15O58__SURFTIMECONST_4O0__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_ACTIVE_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_15O58__SURFTIMECONST_4O0__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_ACTIVE_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

#include "param/env/objects/static/surfer__us_15o58__surftimeconst_4o0__reorientationtime_0o5/group/homogeneous/_member/agent/_active/_passive/choice.h"
// choose your object
#include "param/env/objects/static/surfer__us_15o58__surftimeconst_4o0__reorientationtime_0o5/group/homogeneous/_member/agent/_active/local_axis_swimmer/parameters.h"
#include "core/env/objects/object/active/local_axis_swimmer/core.h"
namespace c0p {
    using SurferUs15O58Surftimeconst4O0Reorientationtime0O5GroupHomogeneousMemberAgentActiveStep = ActiveLocalAxisSwimmerStep<SurferUs15O58Surftimeconst4O0Reorientationtime0O5GroupHomogeneousMemberAgentActiveLocalAxisSwimmerStepParameters, SurferUs15O58Surftimeconst4O0Reorientationtime0O5GroupHomogeneousMemberAgentActivePassiveStep>;
}

#endif
