#ifndef C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_1O0__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_1O0__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

#include "param/env/objects/surfer__us_1o0__surftimeconst_1o0__reorientationtime_0o5/group/homogeneous/_member/agent/_active/choice.h"
// choose your behaviour
#include "param/env/objects/surfer__us_1o0__surftimeconst_1o0__reorientationtime_0o5/group/homogeneous/_member/agent/_behaviour/navigator/choice.h"
namespace c0p {
    using SurferUs1O0Surftimeconst1O0Reorientationtime0O5GroupHomogeneousMemberAgentBehaviour = SurferUs1O0Surftimeconst1O0Reorientationtime0O5GroupHomogeneousMemberAgentBehaviourNavigator<SurferUs1O0Surftimeconst1O0Reorientationtime0O5GroupHomogeneousMemberAgentActiveStep>;
}

#endif
