#ifndef C0P_PARAM_POST_OBJECTS_SURFER__US_15O58__SURFTIMECONST_4O0__REORIENTATIONTIME_0O5_PY_CHOICE_H
#define C0P_PARAM_POST_OBJECTS_SURFER__US_15O58__SURFTIMECONST_4O0__REORIENTATIONTIME_0O5_PY_CHOICE_H
#pragma once

// choose your post processing
#include "core/post/objects/object/post/group/all/core.h"
#include "param/post/objects/surfer__us_15o58__surftimeconst_4o0__reorientationtime_0o5/py/group/all/parameters.h"
namespace c0p {
    template<typename TypeSurferUs15O58Surftimeconst4O0Reorientationtime0O5Step>
    using PostSurferUs15O58Surftimeconst4O0Reorientationtime0O5Py = PostPostGroupAll<PostSurferUs15O58Surftimeconst4O0Reorientationtime0O5PyGroupAllParameters, TypeSurferUs15O58Surftimeconst4O0Reorientationtime0O5Step>;
}

#endif
