#ifndef C0P_PARAM_OBJECTS_SURFER__VS_4O0__SURFTIMECONST_3O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__VS_4O0__SURFTIMECONST_3O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/static/surfer__vs_4o0__surftimeconst_3o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/choice.h"
namespace c0p {
    template<typename SurferVs4O0Surftimeconst3O0GroupHomogeneousMemberAgentActiveStep>
    using SurferVs4O0Surftimeconst3O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity = SurferVs4O0Surftimeconst3O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst<SurferVs4O0Surftimeconst3O0GroupHomogeneousMemberAgentActiveStep>;
}

#endif
