#ifndef C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_2O0__REORIENTATIONTIME_2O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_SENSOR_VELOCITY_GRADIENTS_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_2O0__REORIENTATIONTIME_2O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_SENSOR_VELOCITY_GRADIENTS_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "core/env/objects/object/agent/behaviour/sensor/velocity_gradients/accurate/core.h"
#include "param/env/objects/surfer__us_1o0__surftimeconst_2o0__reorientationtime_2o0/group/homogeneous/_member/agent/_behaviour/_sensor/velocity_gradients/accurate/parameters.h"
namespace c0p {
    template<typename SurferUs1O0Surftimeconst2O0Reorientationtime2O0GroupHomogeneousMemberAgentActiveStep>
    using SurferUs1O0Surftimeconst2O0Reorientationtime2O0GroupHomogeneousMemberAgentBehaviourSensorVelocityGradients = AgentBehaviourSensorVelocityGradientsAccurate<SurferUs1O0Surftimeconst2O0Reorientationtime2O0GroupHomogeneousMemberAgentBehaviourSensorVelocityGradientsAccurateParameters, SurferUs1O0Surftimeconst2O0Reorientationtime2O0GroupHomogeneousMemberAgentActiveStep>;
}

#endif
