#ifndef C0P_PARAM_OBJECTS_SURFER__US_15O58__SURFTIMECONST_4O5__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_TRACKER_BEHAVIOUR_DIRECTION_SURF_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_15O58__SURFTIMECONST_4O5__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_TRACKER_BEHAVIOUR_DIRECTION_SURF_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// behaviour time horizon choice
#include "param/env/objects/static/surfer__us_15o58__surftimeconst_4o5__reorientationtime_0o5/group/homogeneous/_member/agent/_behaviour/tracker/_behaviour_direction/surf/_behaviour_time_horizon/choice.h"
// choose your behaviour
#include "core/env/objects/object/agent/behaviour/tracker/behaviour_direction/surf/core.h"
#include "param/env/objects/static/surfer__us_15o58__surftimeconst_4o5__reorientationtime_0o5/group/homogeneous/_member/agent/_behaviour/tracker/_behaviour_direction/surf/parameters.h"
namespace c0p {
    template<typename SurferUs15O58Surftimeconst4O5Reorientationtime0O5GroupHomogeneousMemberAgentActiveStep>
    using SurferUs15O58Surftimeconst4O5Reorientationtime0O5GroupHomogeneousMemberAgentBehaviourTrackerBehaviourDirectionSurf = AgentBehaviourTrackerBehaviourDirectionSurf<SurferUs15O58Surftimeconst4O5Reorientationtime0O5GroupHomogeneousMemberAgentBehaviourTrackerBehaviourDirectionSurfParameters, SurferUs15O58Surftimeconst4O5Reorientationtime0O5GroupHomogeneousMemberAgentActiveStep, SurferUs15O58Surftimeconst4O5Reorientationtime0O5GroupHomogeneousMemberAgentBehaviourTrackerBehaviourDirectionSurfBehaviourTimeHorizon<SurferUs15O58Surftimeconst4O5Reorientationtime0O5GroupHomogeneousMemberAgentActiveStep>>;
}

#endif
