#ifndef C0P_PARAM_OBJECTS_SURFER__VS_4O0__SURFTIMECONST_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CONST_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__VS_4O0__SURFTIMECONST_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CONST_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "core/env/objects/object/agent/behaviour/navigator/behaviour_velocity/const/core.h"
#include "param/env/objects/static/surfer__vs_4o0__surftimeconst_0o5/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/parameters.h"
namespace c0p {
    template<typename SurferVs4O0Surftimeconst0O5GroupHomogeneousMemberAgentActiveStep>
    using SurferVs4O0Surftimeconst0O5GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst = AgentBehaviourNavigatorBehaviourVelocityConst<SurferVs4O0Surftimeconst0O5GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConstParameters, SurferVs4O0Surftimeconst0O5GroupHomogeneousMemberAgentActiveStep>;
}

#endif
