#ifndef C0P_PARAM_OBJECTS_SURFER__US_8O0__SURFTIMEPREFACTOR_2O25_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CONST_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_8O0__SURFTIMEPREFACTOR_2O25_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CONST_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// sensor choice
#include "param/env/objects/surfer__us_8o0__surftimeprefactor_2o25/group/homogeneous/_member/agent/_behaviour/_sensor/direction/choice.h"
// choose your behaviour
#include "core/env/objects/object/agent/behaviour/navigator/behaviour_velocity/const/core.h"
#include "param/env/objects/surfer__us_8o0__surftimeprefactor_2o25/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/parameters.h"
namespace c0p {
    template<typename SurferUs8O0Surftimeprefactor2O25GroupHomogeneousMemberAgentActiveStep>
    using SurferUs8O0Surftimeprefactor2O25GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst = AgentBehaviourNavigatorBehaviourVelocityConst<SurferUs8O0Surftimeprefactor2O25GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConstParameters, SurferUs8O0Surftimeprefactor2O25GroupHomogeneousMemberAgentActiveStep, SurferUs8O0Surftimeprefactor2O25GroupHomogeneousMemberAgentBehaviourSensorDirection<SurferUs8O0Surftimeprefactor2O25GroupHomogeneousMemberAgentActiveStep>, SurferUs8O0Surftimeprefactor2O25GroupHomogeneousMemberAgentBehaviourSensorVelocityGradients<SurferUs8O0Surftimeprefactor2O25GroupHomogeneousMemberAgentActiveStep>>;
}

#endif
