#ifndef C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_5O0__REORIENTATIONTIME_3O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CONST_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_5O0__REORIENTATIONTIME_3O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CONST_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// sensor choice
#include "param/env/objects/surfer__us_1o0__surftimeconst_5o0__reorientationtime_3o5/group/homogeneous/_member/agent/_behaviour/_sensor/direction/choice.h"
// choose your behaviour
#include "core/env/objects/object/agent/behaviour/navigator/behaviour_velocity/const/core.h"
#include "param/env/objects/surfer__us_1o0__surftimeconst_5o0__reorientationtime_3o5/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/parameters.h"
namespace c0p {
    template<typename SurferUs1O0Surftimeconst5O0Reorientationtime3O5GroupHomogeneousMemberAgentActiveStep>
    using SurferUs1O0Surftimeconst5O0Reorientationtime3O5GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst = AgentBehaviourNavigatorBehaviourVelocityConst<SurferUs1O0Surftimeconst5O0Reorientationtime3O5GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConstParameters, SurferUs1O0Surftimeconst5O0Reorientationtime3O5GroupHomogeneousMemberAgentActiveStep, SurferUs1O0Surftimeconst5O0Reorientationtime3O5GroupHomogeneousMemberAgentBehaviourSensorDirection<SurferUs1O0Surftimeconst5O0Reorientationtime3O5GroupHomogeneousMemberAgentActiveStep>, SurferUs1O0Surftimeconst5O0Reorientationtime3O5GroupHomogeneousMemberAgentBehaviourSensorVelocityGradients<SurferUs1O0Surftimeconst5O0Reorientationtime3O5GroupHomogeneousMemberAgentActiveStep>>;
}

#endif
