#ifndef C0P_PARAM_OBJECTS_SURFER__US_1O5__SURFTIMECONST_8O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_1O5__SURFTIMECONST_8O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// sensor choice
#include "param/env/objects/surfer__us_1o5__surftimeconst_8o0/group/homogeneous/_member/agent/_behaviour/_sensor/direction/choice.h"
#include "param/env/objects/surfer__us_1o5__surftimeconst_8o0/group/homogeneous/_member/agent/_behaviour/_sensor/velocity_gradients/choice.h"
// sub behaviour choice
#include "param/env/objects/surfer__us_1o5__surftimeconst_8o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_direction/choice.h"
#include "param/env/objects/surfer__us_1o5__surftimeconst_8o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/choice.h"
// choose your behaviour
#include "core/env/objects/object/agent/behaviour/navigator/swimmer/core.h"
#include "param/env/objects/surfer__us_1o5__surftimeconst_8o0/group/homogeneous/_member/agent/_behaviour/navigator/swimmer/parameters.h"
namespace c0p {
    template<typename SurferUs1O5Surftimeconst8O0GroupHomogeneousMemberAgentActiveStep>
    using SurferUs1O5Surftimeconst8O0GroupHomogeneousMemberAgentBehaviourNavigator = AgentBehaviourNavigatorSwimmer<SurferUs1O5Surftimeconst8O0GroupHomogeneousMemberAgentBehaviourNavigatorSwimmerParameters, SurferUs1O5Surftimeconst8O0GroupHomogeneousMemberAgentActiveStep, SurferUs1O5Surftimeconst8O0GroupHomogeneousMemberAgentBehaviourSensorDirection<SurferUs1O5Surftimeconst8O0GroupHomogeneousMemberAgentActiveStep>, SurferUs1O5Surftimeconst8O0GroupHomogeneousMemberAgentBehaviourSensorVelocityGradients<SurferUs1O5Surftimeconst8O0GroupHomogeneousMemberAgentActiveStep>, SurferUs1O5Surftimeconst8O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirection<SurferUs1O5Surftimeconst8O0GroupHomogeneousMemberAgentActiveStep>, SurferUs1O5Surftimeconst8O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity<SurferUs1O5Surftimeconst8O0GroupHomogeneousMemberAgentActiveStep>>;
}

#endif
