#ifndef C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_0O3_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_0O3_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// sensor choice
#include "param/env/objects/surfer__us_1o0__surftimeconst_0o3/group/homogeneous/_member/agent/_behaviour/_sensor/direction/choice.h"
#include "param/env/objects/surfer__us_1o0__surftimeconst_0o3/group/homogeneous/_member/agent/_behaviour/_sensor/velocity_gradients/choice.h"
// sub behaviour choice
#include "param/env/objects/surfer__us_1o0__surftimeconst_0o3/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_direction/choice.h"
#include "param/env/objects/surfer__us_1o0__surftimeconst_0o3/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/choice.h"
// choose your behaviour
#include "core/env/objects/object/agent/behaviour/navigator/swimmer/core.h"
#include "param/env/objects/surfer__us_1o0__surftimeconst_0o3/group/homogeneous/_member/agent/_behaviour/navigator/swimmer/parameters.h"
namespace c0p {
    template<typename SurferUs1O0Surftimeconst0O3GroupHomogeneousMemberAgentActiveStep>
    using SurferUs1O0Surftimeconst0O3GroupHomogeneousMemberAgentBehaviourNavigator = AgentBehaviourNavigatorSwimmer<SurferUs1O0Surftimeconst0O3GroupHomogeneousMemberAgentBehaviourNavigatorSwimmerParameters, SurferUs1O0Surftimeconst0O3GroupHomogeneousMemberAgentActiveStep, SurferUs1O0Surftimeconst0O3GroupHomogeneousMemberAgentBehaviourSensorDirection<SurferUs1O0Surftimeconst0O3GroupHomogeneousMemberAgentActiveStep>, SurferUs1O0Surftimeconst0O3GroupHomogeneousMemberAgentBehaviourSensorVelocityGradients<SurferUs1O0Surftimeconst0O3GroupHomogeneousMemberAgentActiveStep>, SurferUs1O0Surftimeconst0O3GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirection<SurferUs1O0Surftimeconst0O3GroupHomogeneousMemberAgentActiveStep>, SurferUs1O0Surftimeconst0O3GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity<SurferUs1O0Surftimeconst0O3GroupHomogeneousMemberAgentActiveStep>>;
}

#endif
