#ifndef C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_9O0__REORIENTATIONTIME_0O25_GROUP_HOMOGENEOUS_MEMBER_AGENT_ACTIVE_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_9O0__REORIENTATIONTIME_0O25_GROUP_HOMOGENEOUS_MEMBER_AGENT_ACTIVE_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

#include "param/env/objects/surfer__us_1o0__surftimeconst_9o0__reorientationtime_0o25/group/homogeneous/_member/agent/_active/_passive/choice.h"
// choose your object
#include "param/env/objects/surfer__us_1o0__surftimeconst_9o0__reorientationtime_0o25/group/homogeneous/_member/agent/_active/local_axis_swimmer/parameters.h"
#include "core/env/objects/object/active/local_axis_swimmer/core.h"
namespace c0p {
    using SurferUs1O0Surftimeconst9O0Reorientationtime0O25GroupHomogeneousMemberAgentActiveStep = ActiveLocalAxisSwimmerStep<SurferUs1O0Surftimeconst9O0Reorientationtime0O25GroupHomogeneousMemberAgentActiveLocalAxisSwimmerStepParameters, SurferUs1O0Surftimeconst9O0Reorientationtime0O25GroupHomogeneousMemberAgentActivePassiveStep>;
}

#endif
