#ifndef C0P_PARAM_POST_OBJECTS_SURFER__US_15O58__SURFTIMECONST_10O0__REORIENTATIONTIME_0O5_PZ_GROUP_MEMBER_CHOICE_H
#define C0P_PARAM_POST_OBJECTS_SURFER__US_15O58__SURFTIMECONST_10O0__REORIENTATIONTIME_0O5_PZ_GROUP_MEMBER_CHOICE_H
#pragma once

// choose your post
#include "param/post/objects/surfer__us_15o58__surftimeconst_10o0__reorientationtime_0o5/pz/group/_member/passive/choice.h"

namespace c0p {
    template<typename TypeMemberStep>
    using PostSurferUs15O58Surftimeconst10O0Reorientationtime0O5PzGroupMember = PostSurferUs15O58Surftimeconst10O0Reorientationtime0O5PzGroupMemberPassive<TypeMemberStep>;
}

#endif
