#ifndef C0P_PARAM_OBJECTS_SURFER__US_15O58__SURFTIMECONST_4O5__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_TRACKER_BEHAVIOUR_VELOCITY_CONST_PARAMETERS_H
#define C0P_PARAM_OBJECTS_SURFER__US_15O58__SURFTIMECONST_4O5__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_TRACKER_BEHAVIOUR_VELOCITY_CONST_PARAMETERS_H
#pragma once

// app includes
#include "core/env/objects/object/agent/behaviour/tracker/behaviour_velocity/const/prop.h"
#include "param/parameters.h"

namespace c0p {

// Parameters of the behaviour that keeps swimming velocity constant
struct SurferUs15O58Surftimeconst4O5Reorientationtime0O5GroupHomogeneousMemberAgentBehaviourTrackerBehaviourVelocityConstParameters {
};

}

#endif
