#ifndef C0P_PARAM_POST_OBJECTS_SURFER__US_1O0__SURFTIMECONST_4O0__REORIENTATIONTIME_3O0_PY_GROUP_MEMBER_CHOICE_H
#define C0P_PARAM_POST_OBJECTS_SURFER__US_1O0__SURFTIMECONST_4O0__REORIENTATIONTIME_3O0_PY_GROUP_MEMBER_CHOICE_H
#pragma once

// choose your post
#include "param/post/objects/surfer__us_1o0__surftimeconst_4o0__reorientationtime_3o0/py/group/_member/passive/choice.h"

namespace c0p {
    template<typename TypeMemberStep>
    using PostSurferUs1O0Surftimeconst4O0Reorientationtime3O0PyGroupMember = PostSurferUs1O0Surftimeconst4O0Reorientationtime3O0PyGroupMemberPassive<TypeMemberStep>;
}

#endif
