#ifndef C0P_CORE_ENV_OBJECTS_OBJECT_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_INERTIAL_SURF_BEHAVIOUR_TIME_HORIZON_CONST_PROP_H
#define C0P_CORE_ENV_OBJECTS_OBJECT_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_INERTIAL_SURF_BEHAVIOUR_TIME_HORIZON_CONST_PROP_H
#pragma once

// app includes
#include "core/env/objects/object/agent/behaviour/navigator/behaviour_direction/inertial_surf/behaviour_time_horizon/prop.h"

namespace c0p {

}

#endif
