#ifndef C0P_PARAM_OBJECTS_SURFER__VS_4O0__SURFTIMECONST_3O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__VS_4O0__SURFTIMECONST_3O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "core/env/objects/object/agent/behaviour/navigator/swimmer/core.h"
#include "param/env/objects/static/surfer__vs_4o0__surftimeconst_3o0/group/homogeneous/_member/agent/_behaviour/navigator/swimmer/parameters.h"
// sensor choice
#include "param/env/objects/static/surfer__vs_4o0__surftimeconst_3o0/group/homogeneous/_member/agent/_behaviour/_sensor/direction/choice.h"
#include "param/env/objects/static/surfer__vs_4o0__surftimeconst_3o0/group/homogeneous/_member/agent/_behaviour/_sensor/velocity_gradients/choice.h"
// sub behaviour choice
#include "param/env/objects/static/surfer__vs_4o0__surftimeconst_3o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_direction/choice.h"
#include "param/env/objects/static/surfer__vs_4o0__surftimeconst_3o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/choice.h"
namespace c0p {
    template<typename SurferVs4O0Surftimeconst3O0GroupHomogeneousMemberAgentActiveStep>
    using SurferVs4O0Surftimeconst3O0GroupHomogeneousMemberAgentBehaviourNavigator = AgentBehaviourNavigatorSwimmer<SurferVs4O0Surftimeconst3O0GroupHomogeneousMemberAgentBehaviourNavigatorSwimmerParameters, SurferVs4O0Surftimeconst3O0GroupHomogeneousMemberAgentActiveStep, SurferVs4O0Surftimeconst3O0GroupHomogeneousMemberAgentBehaviourSensorDirection<SurferVs4O0Surftimeconst3O0GroupHomogeneousMemberAgentActiveStep>, SurferVs4O0Surftimeconst3O0GroupHomogeneousMemberAgentBehaviourSensorVelocityGradients<SurferVs4O0Surftimeconst3O0GroupHomogeneousMemberAgentActiveStep>, SurferVs4O0Surftimeconst3O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirection<SurferVs4O0Surftimeconst3O0GroupHomogeneousMemberAgentActiveStep>, SurferVs4O0Surftimeconst3O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity<SurferVs4O0Surftimeconst3O0GroupHomogeneousMemberAgentActiveStep>>;
}

#endif
