#ifndef C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_8O0__REORIENTATIONTIME_0O25_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_8O0__REORIENTATIONTIME_0O25_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/surfer__us_1o0__surftimeconst_8o0__reorientationtime_0o25/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/choice.h"
namespace c0p {
    template<typename SurferUs1O0Surftimeconst8O0Reorientationtime0O25GroupHomogeneousMemberAgentActiveStep>
    using SurferUs1O0Surftimeconst8O0Reorientationtime0O25GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity = SurferUs1O0Surftimeconst8O0Reorientationtime0O25GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst<SurferUs1O0Surftimeconst8O0Reorientationtime0O25GroupHomogeneousMemberAgentActiveStep>;
}

#endif
