#ifndef C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_1O0__REORIENTATIONTIME_2O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_LOCAl_AXIS_SWIMMER_PARAMETERS_H
#define C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_1O0__REORIENTATIONTIME_2O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_LOCAl_AXIS_SWIMMER_PARAMETERS_H
#pragma once

// app includes
#include "core/env/objects/object/agent/behaviour/navigator/local_axis_swimmer/prop.h"

namespace c0p {

// Parameters of the step of a navigator that controls its swimming direction
// delayed by a finite reorientation time
struct SurferUs1O0Surftimeconst1O0Reorientationtime2O5GroupHomogeneousMemberAgentBehaviourNavigatorLocalAxisSwimmerParameters {

};

}

#endif
