#ifndef C0P_PARAM_OBJECTS_SURFER__US_0O05__SURFTIMECONST_0O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_0O05__SURFTIMECONST_0O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/static/surfer__us_0o05__surftimeconst_0o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/choice.h"
namespace c0p {
    template<typename SurferUs0O05Surftimeconst0O0GroupHomogeneousMemberAgentActiveStep>
    using SurferUs0O05Surftimeconst0O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity = SurferUs0O05Surftimeconst0O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst<SurferUs0O05Surftimeconst0O0GroupHomogeneousMemberAgentActiveStep>;
}

#endif
