#ifndef C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_8O0__REORIENTATIONTIME_4O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_8O0__REORIENTATIONTIME_4O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/surfer__us_1o0__surftimeconst_8o0__reorientationtime_4o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_direction/surf/choice.h"
namespace c0p {
    template<typename SurferUs1O0Surftimeconst8O0Reorientationtime4O0GroupHomogeneousMemberAgentActiveStep>
    using SurferUs1O0Surftimeconst8O0Reorientationtime4O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirection = SurferUs1O0Surftimeconst8O0Reorientationtime4O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirectionSurf<SurferUs1O0Surftimeconst8O0Reorientationtime4O0GroupHomogeneousMemberAgentActiveStep>;
}

#endif
