#ifndef C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_6O0__REORIENTATIONTIME_1O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_1O0__SURFTIMECONST_6O0__REORIENTATIONTIME_1O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

#include "param/env/objects/surfer__us_1o0__surftimeconst_6o0__reorientationtime_1o5/group/homogeneous/_member/agent/_active/choice.h"
// choose your behaviour
#include "param/env/objects/surfer__us_1o0__surftimeconst_6o0__reorientationtime_1o5/group/homogeneous/_member/agent/_behaviour/navigator/choice.h"
namespace c0p {
    using SurferUs1O0Surftimeconst6O0Reorientationtime1O5GroupHomogeneousMemberAgentBehaviour = SurferUs1O0Surftimeconst6O0Reorientationtime1O5GroupHomogeneousMemberAgentBehaviourNavigator<SurferUs1O0Surftimeconst6O0Reorientationtime1O5GroupHomogeneousMemberAgentActiveStep>;
}

#endif
