#ifndef C0P_PARAM_OBJECTS_OBJECT_PAIR_A_AGENT_BEHAVIOUR_SWIM_IN_DIRECTION_SWIMMING_DIRECTION_BEHAVIOUR_DIRECTION_SURF_EXP_PARAMETERS_H
#define C0P_PARAM_OBJECTS_OBJECT_PAIR_A_AGENT_BEHAVIOUR_SWIM_IN_DIRECTION_SWIMMING_DIRECTION_BEHAVIOUR_DIRECTION_SURF_EXP_PARAMETERS_H
#pragma once

// app includes
#include "core/env/objects/object/agent/behaviour/swim_in_direction/swimming_direction/behaviour_direction/surf/exp/prop.h"
#include "param/env/objects/object/pair/_a/agent/_behaviour/swim_in_direction/swimming_direction/_behaviour_direction/surf/parameters.h"
#include "param/parameters.h"

namespace c0p {

struct ObjectPairAAgentBehaviourSwimInDirectionSwimmingDirectionBehaviourDirectionSurfExpParameters : public ObjectPairAAgentBehaviourSwimInDirectionSwimmingDirectionBehaviourDirectionSurfParameters {
};

}

#endif
