#ifndef C0P_PARAM_OBJECTS_SURFER__US_3O5__SURFTIMECONST_1O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_3O5__SURFTIMECONST_1O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/surfer__us_3o5__surftimeconst_1o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_direction/surf/choice.h"
namespace c0p {
    template<typename SurferUs3O5Surftimeconst1O0GroupHomogeneousMemberAgentActiveStep>
    using SurferUs3O5Surftimeconst1O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirection = SurferUs3O5Surftimeconst1O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirectionSurf<SurferUs3O5Surftimeconst1O0GroupHomogeneousMemberAgentActiveStep>;
}

#endif
