#ifndef C0P_PARAM_OBJECTS_SURFER__US_8O0__SURFTIMEPREFACTOR_0O75_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_8O0__SURFTIMEPREFACTOR_0O75_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/surfer__us_8o0__surftimeprefactor_0o75/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/choice.h"
namespace c0p {
    template<typename SurferUs8O0Surftimeprefactor0O75GroupHomogeneousMemberAgentActiveStep>
    using SurferUs8O0Surftimeprefactor0O75GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity = SurferUs8O0Surftimeprefactor0O75GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst<SurferUs8O0Surftimeprefactor0O75GroupHomogeneousMemberAgentActiveStep>;
}

#endif
