#ifndef C0P_PARAM_OBJECTS_SURFER__VS_1O0__SURFTIMECONST_1O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CONST_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__VS_1O0__SURFTIMECONST_1O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CONST_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "core/env/objects/object/agent/behaviour/navigator/behaviour_velocity/const/core.h"
#include "param/env/objects/static/surfer__vs_1o0__surftimeconst_1o5/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/parameters.h"
namespace c0p {
    template<typename SurferVs1O0Surftimeconst1O5GroupHomogeneousMemberAgentActiveStep>
    using SurferVs1O0Surftimeconst1O5GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst = AgentBehaviourNavigatorBehaviourVelocityConst<SurferVs1O0Surftimeconst1O5GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConstParameters, SurferVs1O0Surftimeconst1O5GroupHomogeneousMemberAgentActiveStep>;
}

#endif
