#ifndef C0P_PARAM_OBJECTS_SURFER__US_15O0__SURFTIMECONST_0O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_15O0__SURFTIMECONST_0O0_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_VELOCITY_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/surfer__us_15o0__surftimeconst_0o0/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/const/choice.h"
namespace c0p {
    template<typename SurferUs15O0Surftimeconst0O0GroupHomogeneousMemberAgentActiveStep>
    using SurferUs15O0Surftimeconst0O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity = SurferUs15O0Surftimeconst0O0GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocityConst<SurferUs15O0Surftimeconst0O0GroupHomogeneousMemberAgentActiveStep>;
}

#endif
