#ifndef C0P_PARAM_INIT_OBJECTS_SURFER__US_15O58__SURFTIMECONST_2O5__REORIENTATIONTIME_0O5_ORIENT_GROUP_MEMBER_PASSIVE_POS_RANDOM_PARAMETERS_H
#define C0P_PARAM_INIT_OBJECTS_SURFER__US_15O58__SURFTIMECONST_2O5__REORIENTATIONTIME_0O5_ORIENT_GROUP_MEMBER_PASSIVE_POS_RANDOM_PARAMETERS_H
#pragma once

// app include
#include "core/init/objects/object/init/passive/axis/random/prop.h"

namespace c0p {

// Random object orientation initialisation parameters
struct InitSurferUs15O58Surftimeconst2O5Reorientationtime0O5OrientGroupMemberPassiveAxisRandomParameters {
};

}

#endif
