#ifndef C0P_PARAM_OBJECTS_SURFER__US_15O58__SURFTIMECONST_0O5__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_TRACKER_BEHAVIOUR_DIRECTION_SURF_PARAMETERS_H
#define C0P_PARAM_OBJECTS_SURFER__US_15O58__SURFTIMECONST_0O5__REORIENTATIONTIME_0O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_TRACKER_BEHAVIOUR_DIRECTION_SURF_PARAMETERS_H
#pragma once

// app includes
#include "core/env/objects/object/agent/behaviour/tracker/behaviour_direction/surf/prop.h"
#include "param/parameters.h"

namespace c0p {

// Parameters of the behaviour of a surfer that used the default Eigen matrix exponential
struct SurferUs15O58Surftimeconst0O5Reorientationtime0O5GroupHomogeneousMemberAgentBehaviourTrackerBehaviourDirectionSurfParameters {
};

}

#endif
