#ifndef C0P_PARAM_POST_OBJECTS_SURFER__US_15O58__SURFTIMECONST_2O0__REORIENTATIONTIME_0O5_PZ_GROUP_MEMBER_PASSIVE_CHOICE_H
#define C0P_PARAM_POST_OBJECTS_SURFER__US_15O58__SURFTIMECONST_2O0__REORIENTATIONTIME_0O5_PZ_GROUP_MEMBER_PASSIVE_CHOICE_H
#pragma once

// choose your post
#include "core/post/objects/object/post/passive/position/core.h"
#include "param/post/objects/surfer__us_15o58__surftimeconst_2o0__reorientationtime_0o5/pz/group/_member/passive/position/parameters.h"

namespace c0p {
    template<typename TypeSurferUs15O58Surftimeconst2O0Reorientationtime0O5Step>
    using PostSurferUs15O58Surftimeconst2O0Reorientationtime0O5PzGroupMemberPassive = PostPostPassivePosition<PostSurferUs15O58Surftimeconst2O0Reorientationtime0O5PzGroupMemberPassivePositionParameters, TypeSurferUs15O58Surftimeconst2O0Reorientationtime0O5Step>;
}

#endif
