#ifndef C0P_PARAM_POST_OBJECTS_SURFER__US_1O0__SURFTIMECONST_8O0__REORIENTATIONTIME_1O5_PY_GROUP_MEMBER_CHOICE_H
#define C0P_PARAM_POST_OBJECTS_SURFER__US_1O0__SURFTIMECONST_8O0__REORIENTATIONTIME_1O5_PY_GROUP_MEMBER_CHOICE_H
#pragma once

// choose your post
#include "param/post/objects/surfer__us_1o0__surftimeconst_8o0__reorientationtime_1o5/py/group/_member/passive/choice.h"

namespace c0p {
    template<typename TypeMemberStep>
    using PostSurferUs1O0Surftimeconst8O0Reorientationtime1O5PyGroupMember = PostSurferUs1O0Surftimeconst8O0Reorientationtime1O5PyGroupMemberPassive<TypeMemberStep>;
}

#endif
