#ifndef C0P_PARAM_OBJECTS_SURFER__US_0O1__SURFTIMECONST_0O9_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__US_0O1__SURFTIMECONST_0O9_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_BEHAVIOUR_DIRECTION_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "param/env/objects/surfer__us_0o1__surftimeconst_0o9/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_direction/surf/choice.h"
namespace c0p {
    template<typename SurferUs0O1Surftimeconst0O9GroupHomogeneousMemberAgentActiveStep>
    using SurferUs0O1Surftimeconst0O9GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirection = SurferUs0O1Surftimeconst0O9GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirectionSurf<SurferUs0O1Surftimeconst0O9GroupHomogeneousMemberAgentActiveStep>;
}

#endif
