#!/usr/bin/env python3
import sys
import os

def main():
    script_path = __file__
    script_dir = os.path.dirname(script_path)
    script_name = os.path.basename(script_path)

    if os.path.exists(script_dir + "/switch_to_cli"):
        interface = "gui"
    else:
        interface = "cli"

    if os.path.exists("../../bin/activate"):
        os.system("bash -c 'source {script_dir}/../../bin/activate && {script_dir}/.{interface}_generate_new_case {argv}'".format(script_dir=script_dir, interface=interface, argv=" ".join(sys.argv[1:])))
    else:
        print("WARNING: Can't find the standard sheld0n virtual environment. Trying to execute anyway.")
        os.system("{script_dir}/.{interface}_generate_new_case {argv}".format(script_dir=script_dir, interface=interface, argv=" ".join(sys.argv[1:])))

if __name__ == '__main__':
    main()
