#!/usr/bin/env python3
from gooey import Gooey

if __name__ == '__main__': 
    __name__ = ""
    exec(open(".cli_generate_new_case").read())
    __name__ = "__main__"
else:
    exec(open(".cli_generate_new_case").read())

@Gooey(
    show_success_modal=False
)
def main_gui():
    main(True)

if __name__ == '__main__':
    main_gui()
