#!/usr/bin/env python3
import os

def main():
    script_path = os.path.realpath(__file__)
    script_dir = os.path.dirname(script_path)
    script_name = os.path.basename(script_path)
    # # rename gui and cli
    # for dirpath, dirnames, filenames in os.walk(script_dir):
    #     for filename in filenames:
    #         if filename.startswith("gui"):
    #             old_path = os.path.join(dirpath, filename)
    #             new_filename = f".{filename}"
    #             new_path = os.path.join(dirpath, new_filename)
    #             # Rename the file
    #             os.rename(old_path, new_path)
    #         if filename.startswith(".cli"):
    #             old_path = os.path.join(dirpath, filename)
    #             new_filename = filename[1:]
    #             new_path = os.path.join(dirpath, new_filename)
    #             # Rename the file
    #             os.rename(old_path, new_path)
    # hide self
    new_name = "." + script_name
    new_path = os.path.join(script_dir, new_name)
    os.rename(script_path, new_path)
    # show other
    other_name = ".switch_to_gui"
    new_other_name = other_name[1:]
    other_path = os.path.join(script_dir, other_name)
    new_other_path = os.path.join(script_dir, new_other_name)
    os.rename(other_path, new_other_path)

if __name__ == '__main__':
    main()
