#ifndef C0P_PARAM_POST_OBJECTS_SURFER__US_1O0__SURFTIMECONST_6O0__REORIENTATIONTIME_1O5_PY_GROUP_MEMBER_PASSIVE_CHOICE_H
#define C0P_PARAM_POST_OBJECTS_SURFER__US_1O0__SURFTIMECONST_6O0__REORIENTATIONTIME_1O5_PY_GROUP_MEMBER_PASSIVE_CHOICE_H
#pragma once

// choose your post
#include "core/post/objects/object/post/passive/position/core.h"
#include "param/post/objects/surfer__us_1o0__surftimeconst_6o0__reorientationtime_1o5/py/group/_member/passive/position/parameters.h"

namespace c0p {
    template<typename TypeSurferUs1O0Surftimeconst6O0Reorientationtime1O5Step>
    using PostSurferUs1O0Surftimeconst6O0Reorientationtime1O5PyGroupMemberPassive = PostPostPassivePosition<PostSurferUs1O0Surftimeconst6O0Reorientationtime1O5PyGroupMemberPassivePositionParameters, TypeSurferUs1O0Surftimeconst6O0Reorientationtime1O5Step>;
}

#endif
