#ifndef C0P_PARAM_OBJECTS_SURFER__VS_4O0__SURFTIMECONST_2O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_CHOICE_H
#define C0P_PARAM_OBJECTS_SURFER__VS_4O0__SURFTIMECONST_2O5_GROUP_HOMOGENEOUS_MEMBER_AGENT_BEHAVIOUR_NAVIGATOR_CHOICE_H
#pragma once

// THIS FILE SHOULD NOT BE EDITED DIRECTLY BY THE USERS.
// THIS FILE WILL BE AUTOMATICALLY EDITED WHEN THE
// CHOOSE COMMAND IS USED

// choose your behaviour
#include "core/env/objects/object/agent/behaviour/navigator/swimmer/core.h"
#include "param/env/objects/static/surfer__vs_4o0__surftimeconst_2o5/group/homogeneous/_member/agent/_behaviour/navigator/swimmer/parameters.h"
// sensor choice
#include "param/env/objects/static/surfer__vs_4o0__surftimeconst_2o5/group/homogeneous/_member/agent/_behaviour/_sensor/direction/choice.h"
#include "param/env/objects/static/surfer__vs_4o0__surftimeconst_2o5/group/homogeneous/_member/agent/_behaviour/_sensor/velocity_gradients/choice.h"
// sub behaviour choice
#include "param/env/objects/static/surfer__vs_4o0__surftimeconst_2o5/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_direction/choice.h"
#include "param/env/objects/static/surfer__vs_4o0__surftimeconst_2o5/group/homogeneous/_member/agent/_behaviour/navigator/_behaviour_velocity/choice.h"
namespace c0p {
    template<typename SurferVs4O0Surftimeconst2O5GroupHomogeneousMemberAgentActiveStep>
    using SurferVs4O0Surftimeconst2O5GroupHomogeneousMemberAgentBehaviourNavigator = AgentBehaviourNavigatorSwimmer<SurferVs4O0Surftimeconst2O5GroupHomogeneousMemberAgentBehaviourNavigatorSwimmerParameters, SurferVs4O0Surftimeconst2O5GroupHomogeneousMemberAgentActiveStep, SurferVs4O0Surftimeconst2O5GroupHomogeneousMemberAgentBehaviourSensorDirection<SurferVs4O0Surftimeconst2O5GroupHomogeneousMemberAgentActiveStep>, SurferVs4O0Surftimeconst2O5GroupHomogeneousMemberAgentBehaviourSensorVelocityGradients<SurferVs4O0Surftimeconst2O5GroupHomogeneousMemberAgentActiveStep>, SurferVs4O0Surftimeconst2O5GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourDirection<SurferVs4O0Surftimeconst2O5GroupHomogeneousMemberAgentActiveStep>, SurferVs4O0Surftimeconst2O5GroupHomogeneousMemberAgentBehaviourNavigatorBehaviourVelocity<SurferVs4O0Surftimeconst2O5GroupHomogeneousMemberAgentActiveStep>>;
}

#endif
